namespace WowViewer.Core.Runtime.World;

public readonly record struct WorldRenderStageStats(double DurationMs, int VisibleCount = 0, int SubmittedCount = 0);

public readonly record struct WorldRenderFrameStats(
    double TotalCpuMs,
    int PendingAssetLoadCount,
    int TerrainChunksRendered,
    int TerrainChunksCulled,
    int WdlVisibleTileCount,
    int WdlHiddenTileCount,
    int VisibleWmoCount,
    int VisibleMdxCount,
    int VisibleTaxiMdxCount,
    int OpaqueBatchedMdxCount,
    int OpaqueUnbatchedMdxCount,
    int TransparentBatchedMdxCount,
    int TransparentUnbatchedMdxCount,
    int WmoDrawCallCount,
    int WmoBatchDrawCallCount,
    int WmoGroupFallbackDrawCallCount,
    int WmoLiquidDrawCallCount,
    int WmoDoodadSubmissionCount,
    int WmoVisibleGroupSubmissionCount,
    WorldRenderStageStats DeferredAssetLoads,
    WorldRenderStageStats TaxiActorUpdate,
    WorldRenderStageStats Lighting,
    WorldRenderStageStats Sky,
    WorldRenderStageStats SkyboxBackdrop,
    WorldRenderStageStats Wdl,
    WorldRenderStageStats Terrain,
    WorldRenderStageStats WmoVisibility,
    WorldRenderStageStats WmoSubmission,
    WorldRenderStageStats WmoTransparentSubmission,
    WorldRenderStageStats MdxAnimation,
    WorldRenderStageStats MdxVisibility,
    WorldRenderStageStats MdxOpaqueSubmission,
    WorldRenderStageStats Liquid,
    WorldRenderStageStats MdxTransparentSort,
    WorldRenderStageStats MdxTransparentSubmission,
    WorldRenderStageStats Overlay,
    WorldRenderStageStats SceneMaintenance)
{
    public static WorldRenderFrameStats Empty { get; } = new(
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0),
        new WorldRenderStageStats(0));
}
