using System.Diagnostics;
using System.Numerics;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using ImGuiNET;
using WowViewer.Core.IO.Mdx;
using WoWViewer.DataSources;
using WoWViewer.Export;
using WoWViewer.Logging;
using WoWViewer.Rendering;
using WoWViewer.Catalog;
using WoWViewer.Capture;
using WoWViewer.Population;
using WoWViewer.Terrain;
using Silk.NET.Input;
using Silk.NET.Maths;
using Silk.NET.OpenGL;
using Silk.NET.OpenGL.Extensions.ImGui;
using Silk.NET.Windowing;
using WowViewer.Core.IO.Files;
using WowViewer.Core.IO.Maps;
using WowViewer.Core.Maps;
using WoWViewer.Terrain.Vlm;
using WowViewer.Core.IO.M2;
using WowViewer.Core.IO.M2Chunked;
using WowViewer.Core.IO.M2Era1121;
using WowViewer.Core.M2;
using WowViewer.Core.Runtime.M2;
using WowViewer.Core.Runtime.Marketing;
using WowViewer.Core.Runtime.World.Visibility;
using ObjectInstance = WowViewer.Core.Runtime.World.WorldObjectInstance;
using WowViewer.Core.IO.Converters;
using WoWViewer.Workbench;
using CoreMdxCollisionSummary = WowViewer.Core.Mdx.MdxCollisionSummary;
using CoreMdxGeometryFile = WowViewer.Core.Mdx.MdxGeometryFile;
using CoreMdxSummary = WowViewer.Core.Mdx.MdxSummary;
using CorePm4DocumentReader = WowViewer.Core.PM4.Services.Pm4ResearchReader;
using Pm4CoordinateService = WowViewer.Core.PM4.Services.Pm4CoordinateService;
using WowViewer.Core.Mdx;
using System.ComponentModel;
using System.Linq;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using WowViewer.Core.Editor;
using WowViewer.Core.Editor.Bridge;
using WowViewer.Core.Editor.Eras;
using WowViewer.Core.Editor.Logging;
using WowViewer.Core.Editor.Operations;
using WowViewer.Core.Editor.Plugins;
using WowViewer.Core.Editor.Session;
using WowViewer.Core.PM4.Matching;
using WowViewer.Core.PM4.Reconciliation;
using WowViewer.Core.PM4.Services;
using WowViewer.Core.IO.Terrain;
using WowViewer.Core.Runtime.World;
using WoWViewer.UI;
using WowViewer.Core.Runtime.World.Minimap;
using System.IO;
using WowViewer.Core.IO.Dbc;
using System;
using WowViewer.Core.Runtime.World.Passes;
using System.Globalization;
using WowViewer.Core.IO.Casc;

namespace WoWViewer;

/// <summary>
/// ViewerApp's implementation of <see cref="IViewerAppHost"/> (Epic 251 U-01): the only way the
/// extracted services reach ViewerApp state. Each member forwards to a ViewerApp field or method, or
/// to the service that now owns it. Plumbing only; features live in Workbench/Services.
/// </summary>
public partial class ViewerApp
{
    ref IDataSource? IViewerAppHost.DataSource => ref _dataSource;
    ref string? IViewerAppHost.LoadedFilePath => ref _loadedFilePath;
    ref string IViewerAppHost.MapConvertLkMapDir => ref _mapConvertLkMapDir;
    ref string IViewerAppHost.MapConvertOutputDir => ref _mapConvertOutputDir;
    ref string IViewerAppHost.MapConvertProjectSourceKey => ref _mapConvertProjectSourceKey;
    ref string IViewerAppHost.MapConvertSourcePath => ref _mapConvertSourcePath;
    ref string IViewerAppHost.ProjectOutputRootDir => ref _projectOutputRootDir;
    ref bool IViewerAppHost.ShowMapConverterDialog => ref _showMapConverterDialog;
    ref bool IViewerAppHost.ShowWmoConverterDialog => ref _showWmoConverterDialog;
    ref string IViewerAppHost.WmoConvertSourcePath => ref _wmoConvertSourcePath;
    string IViewerAppHost.GetProjectOutputRootDirectory() => _projectOutput.GetProjectOutputRootDirectory();
    void IViewerAppHost.HandleProjectOutputRootChanged() => _projectOutput.HandleProjectOutputRootChanged();
    void IViewerAppHost.LoadWdtTerrain(string wdtPath) => _worldLoader.LoadWdtTerrain(wdtPath);
    ref string IViewerAppHost.MkHarvestDatasetRoot => ref _mkHarvestDatasetRoot;
    ref int IViewerAppHost.MkHarvestViewerValidationCompleted => ref _mkHarvestViewerValidationCompleted;
    ref int IViewerAppHost.MkHarvestViewerValidationFailed => ref _mkHarvestViewerValidationFailed;
    ref int IViewerAppHost.MkHarvestViewerValidationQueued => ref _mkHarvestViewerValidationQueued;
    ref CaptureAutomationService.MkHarvestViewerValidationCapturePlan? IViewerAppHost.PendingMkHarvestViewerValidationCapturePlan => ref _captureAutomation._pendingMkHarvestViewerValidationCapturePlan;
    ref bool IViewerAppHost.ShowTerrainTextureTransferDialog => ref _showTerrainTextureTransferDialog;
    ref bool IViewerAppHost.ShowVlmExportDialog => ref _showVlmExportDialog;
    ref string IViewerAppHost.TerrainTransferOutputDir => ref _terrainTransferOutputDir;
    ref string IViewerAppHost.TerrainTransferSourceDir => ref _terrainTransferSourceDir;
    ref string IViewerAppHost.TerrainTransferTargetDir => ref _terrainTransferTargetDir;
    ref string IViewerAppHost.VlmClientPath => ref _vlmClientPath;
    ref string IViewerAppHost.VlmMapName => ref _vlmMapName;
    ref string IViewerAppHost.VlmOutputDir => ref _vlmOutputDir;
    ref VlmTerrainManager? IViewerAppHost.VlmTerrainManager => ref _vlmTerrainManager;
    void IViewerAppHost.LoadVlmProject(string projectRoot) => _worldLoader.LoadVlmProject(projectRoot);
    void IViewerAppHost.StitchMkHarvestViewerValidationOutputs(string mapName, string outputDirectory, string noLiquidsOutputDirectory, string noObjectsOutputDirectory, string objectsOnlyOutputDirectory, int requestedResolution) => _captureAutomation.StitchMkHarvestViewerValidationOutputs(mapName, outputDirectory, noLiquidsOutputDirectory, noObjectsOutputDirectory, objectsOnlyOutputDirectory, requestedResolution);
    HashSet<(int tileX, int tileY, int chunkX, int chunkY)> IViewerAppHost.SelectedChunks => _selectedChunks;
    ref WowViewer.Core.Runtime.World.Terrain.Stratigraphy.StratigraphyAnchorMode IViewerAppHost.StratigraphyAnchorMode => ref _stratigraphyAnchorMode;
    ref bool IViewerAppHost.StratigraphyPolarityInverted => ref _stratigraphyPolarityInverted;
    ref bool IViewerAppHost.StratigraphyPreserveNegativeFloor => ref _stratigraphyPreserveNegativeFloor;
    ref bool IViewerAppHost.StratigraphyUnhideDevMeshes => ref _stratigraphyUnhideDevMeshes;
    ref bool IViewerAppHost.StratigraphyUseNeighborAutoFit => ref _stratigraphyUseNeighborAutoFit;
    ref bool IViewerAppHost.StratigraphyUseWdlMagnetization => ref _stratigraphyUseWdlMagnetization;
    ref float IViewerAppHost.StratigraphyWdlMagnetizationStrength => ref _stratigraphyWdlMagnetizationStrength;
    ref TerrainManager? IViewerAppHost.TerrainManager => ref _terrainManager;
    ref TerrainTileScope IViewerAppHost.TerrainTileScope => ref _terrainTileScope;
    ref bool IViewerAppHost.TerrainWeakSignalRestoreAllLoadedTiles => ref _terrainWeakSignalRestoreAllLoadedTiles;
    ref float IViewerAppHost.TerrainWeakSignalRestoreCandidateMaxHeight => ref _terrainWeakSignalRestoreCandidateMaxHeight;
    ref float IViewerAppHost.TerrainWeakSignalRestoreCandidateMinHeight => ref _terrainWeakSignalRestoreCandidateMinHeight;
    ref bool IViewerAppHost.TerrainWeakSignalRestoreEnabled => ref _terrainWeakSignalRestoreEnabled;
    ref float IViewerAppHost.TerrainWeakSignalRestoreManualFactor => ref _terrainWeakSignalRestoreManualFactor;
    ref string IViewerAppHost.TerrainWeakSignalRestoreStatus => ref _terrainWeakSignalRestoreStatus;
    ref bool IViewerAppHost.TerrainWeakSignalRestoreUseAutoFactor => ref _terrainWeakSignalRestoreUseAutoFactor;
    ref bool IViewerAppHost.TerrainWeakSignalRestoreUseTextureSubdivisions => ref _terrainWeakSignalRestoreUseTextureSubdivisions;
    ref WdlPreviewCacheService? IViewerAppHost.WdlPreviewCacheService => ref _wdlPreviewCacheService;
    (int tileX, int tileY) IViewerAppHost.GetCameraTile() => GetCameraTile();
    string? IViewerAppHost.GetCurrentSessionMapName() => _dataSourceSession.GetCurrentSessionMapName();
    IReadOnlyList<(int tileX, int tileY)> IViewerAppHost.GetTileScopeList(TerrainTileScope scope) => _terrainTileIo.GetTileScopeList(scope);
    ref TerrainTileScope IViewerAppHost.MapGlbScope => ref _mapGlbScope;
    ref Md5TranslateIndex? IViewerAppHost.Md5Index => ref _md5Index;
    ref bool IViewerAppHost.ShowAlphaFolderImportScope => ref _showAlphaFolderImportScope;
    ref bool IViewerAppHost.ShowHeightmapFolderImportScope => ref _showHeightmapFolderImportScope;
    ref bool IViewerAppHost.ShowMccvFolderImportScope => ref _showMccvFolderImportScope;
    ref string IViewerAppHost.StatusMessage => ref _statusMessage;
    ref TerrainExportKind IViewerAppHost.TerrainExportKind => ref _terrainExportKind;
    ref TerrainImportKind IViewerAppHost.TerrainImportKind => ref _terrainImportKind;
    ref int IViewerAppHost.TerrainTileRangeEndX => ref _terrainTileRangeEndX;
    ref int IViewerAppHost.TerrainTileRangeEndY => ref _terrainTileRangeEndY;
    ref int IViewerAppHost.TerrainTileRangeStartX => ref _terrainTileRangeStartX;
    ref int IViewerAppHost.TerrainTileRangeStartY => ref _terrainTileRangeStartY;
    TerrainWeakSignalRestoreService IViewerAppHost.TerrainWeakSignalRestore => _terrainWeakSignalRestore;
    ref Camera IViewerAppHost.Camera => ref _camera;
    ref ChunkClipboard? IViewerAppHost.ChunkClipboard => ref _chunkClipboard;
    ref (int tileX, int tileY, int chunkX, int chunkY)? IViewerAppHost.ChunkClipboardCopiedKey => ref _chunkClipboardCopiedKey;
    ref (int tileX, int tileY, int chunkX, int chunkY)? IViewerAppHost.ChunkClipboardLockedTargetKey => ref _chunkClipboardLockedTargetKey;
    ref ChunkClipboardSet? IViewerAppHost.ChunkClipboardSet => ref _chunkClipboardSet;
    ref bool IViewerAppHost.ChunkClipboardShowOverlay => ref _chunkClipboardShowOverlay;
    ref string IViewerAppHost.ChunkClipboardStatus => ref _chunkClipboardStatus;
    ref bool IViewerAppHost.ChunkToolEnabled => ref _chunkToolEnabled;
    TerrainTileIoService IViewerAppHost.TerrainTileIo => _terrainTileIo;
    string IViewerAppHost.EnsureEditorProjectOutputDirectory(bool forceNew) => _projectOutput.EnsureEditorProjectOutputDirectory(forceNew);
    string IViewerAppHost.GetEditorProjectName(string? fallbackName) => _projectOutput.GetEditorProjectName(fallbackName);
    string? IViewerAppHost.GetEditorProjectSourceKey() => _projectOutput.GetEditorProjectSourceKey();
    bool IViewerAppHost.TryPickTerrainChunkUnderMouse(TerrainRenderer renderer, out TerrainRenderer.TerrainChunkInfo info) => _terrainQuery.TryPickTerrainChunkUnderMouse(renderer, out info);
    ref string IViewerAppHost.EditorProjectOutputDir => ref _editorProjectOutputDir;
    ref string IViewerAppHost.SelectedPlacementSaveStatus => ref _selectedPlacementSaveStatus;
    ref string? IViewerAppHost.SelectedPlacementSaveTargetPath => ref _selectedPlacementSaveTargetPath;
    ref WorldScene? IViewerAppHost.WorldScene => ref _worldScene;
    void IViewerAppHost.RefreshSelectedWorldObjectInfo() => RefreshSelectedWorldObjectInfo();
    ref int IViewerAppHost.CurrentMapId => ref _currentMapId;
    ref bool IViewerAppHost.SqlForceStreamRefresh => ref _sqlForceStreamRefresh;
    ref SqlWorldPopulationService? IViewerAppHost.SqlPopulationService => ref _sqlPopulationService;
    void IViewerAppHost.DrawToolbarPopupButton(string label, string summary, string popupId, Action drawContent) => _viewerChrome.DrawToolbarPopupButton(label, summary, popupId, drawContent);
    void IViewerAppHost.ExportAnimationStateJson(IAnimationController animator, int currentSeq, string currentSeqName, float seqStart, float seqEnd) => _modelInspector.ExportAnimationStateJson(animator, currentSeq, currentSeqName, seqStart, seqEnd);
    ref string? IViewerAppHost.LastVirtualPath => ref _lastVirtualPath;
    Dictionary<string, Dictionary<int, string>> IViewerAppHost.SavedTaxiActorModelOverridesByMap => _savedTaxiActorModelOverridesByMap;
    ref int IViewerAppHost.SelectedAreaPoiId => ref _selectedAreaPoiId;
    ref int IViewerAppHost.SelectedObjectIndex => ref _selectedObjectIndex;
    ref string IViewerAppHost.SelectedObjectInfo => ref _selectedObjectInfo;
    ref string IViewerAppHost.SelectedObjectType => ref _selectedObjectType;
    ref string IViewerAppHost.TaxiActorModelOverrideInput => ref _taxiActorModelOverrideInput;
    ref int IViewerAppHost.TaxiActorModelOverrideInputRouteId => ref _taxiActorModelOverrideInputRouteId;
    ref int IViewerAppHost.TaxiActorModelOverrideTargetRouteId => ref _taxiActorModelOverrideTargetRouteId;
    void IViewerAppHost.SaveViewerSettings() => _settings.SaveViewerSettings();
    bool IViewerAppHost.TryGetSelectedBrowserModelPath(out string assetPath) => _navigatorPanel.TryGetSelectedBrowserModelPath(out assetPath);
    ref EditorWorkspaceTask IViewerAppHost.EditorWorkspaceTask => ref _editorWorkspaceTask;
    ref float IViewerAppHost.FovDegrees => ref _fovDegrees;
    ref GL IViewerAppHost.Gl => ref _gl;
    ref Pm4ObjectMatchObject? IViewerAppHost.HoveredPm4ObjectMatch => ref _hoveredPm4ObjectMatch;
    ref int IViewerAppHost.HoveredPm4ObjectMatchCacheMaxMatches => ref _hoveredPm4ObjectMatchCacheMaxMatches;
    ref (int tileX, int tileY, uint ck24, int objectPart)? IViewerAppHost.HoveredPm4ObjectMatchKey => ref _hoveredPm4ObjectMatchKey;
    ref float IViewerAppHost.LastMouseX => ref _lastMouseX;
    ref float IViewerAppHost.LastMouseY => ref _lastMouseY;
    ref int IViewerAppHost.Pm4ObjectMatchMaxMatchesPerObject => ref _pm4ObjectMatchMaxMatchesPerObject;
    ref SceneClusterSelector3D? IViewerAppHost.SceneClusterSelector3D => ref _sceneClusterSelector3D;
    ref SceneCursorRenderer? IViewerAppHost.SceneCursorRenderer => ref _sceneCursorRenderer;
    TaxiAndAreaPoiSelectionService IViewerAppHost.TaxiAndAreaPoi => _taxiAndAreaPoi;
    ref InvestigationService.VisualInvestigationMode IViewerAppHost.VisualInvestigationMode => ref _investigation._visualInvestigationMode;
    ref WorkspaceMode IViewerAppHost.WorkspaceMode => ref _workspaceMode;
    bool IViewerAppHost.CanSceneConsumeMouse(float x, float y) => _shellLayout.CanSceneConsumeMouse(x, y);
    void IViewerAppHost.ClearSelectedWlLiquidBody(bool clearListIsolation) => _investigation.ClearSelectedWlLiquidBody(clearListIsolation);
    float IViewerAppHost.GetSceneFarPlane() => _terrainQuery.GetSceneFarPlane();
    bool IViewerAppHost.IsSceneMouseCaptureBlocked(float x, float y) => _shellLayout.IsSceneMouseCaptureBlocked(x, y);
    void IViewerAppHost.SelectTerrainChunkFromClick(TerrainRenderer.TerrainChunkInfo info) => _terrainInspection.SelectTerrainChunkFromClick(info);
    void IViewerAppHost.SetSelectedWlLiquidBody(WlLiquidBody body, bool isolateInList, bool focusInspectWorkspace, string? statusMessage) => _investigation.SetSelectedWlLiquidBody(body, isolateInList, focusInspectWorkspace, statusMessage);
    bool IViewerAppHost.ShouldShowHoveredAssetInfoForInvestigation(HoveredAssetInfo info) => _investigation.ShouldShowHoveredAssetInfoForInvestigation(info);
    bool IViewerAppHost.TogglePm4ObjectCollectionMembership((int tileX, int tileY, uint ck24, int objectPart) key, bool reportStatus, bool removeIfPresent) => _pm4Workbench.TogglePm4ObjectCollectionMembership(key, reportStatus, removeIfPresent);
    bool IViewerAppHost.TryFindWlLiquidBodyByKey(string bodyKey, out WlLiquidBody? body) => _investigation.TryFindWlLiquidBodyByKey(bodyKey, out body);
    bool IViewerAppHost.TryGetSceneViewportRect(out float x, out float y, out float width, out float height) => _shellLayout.TryGetSceneViewportRect(out x, out y, out width, out height);
    bool IViewerAppHost.TryRaycastTerrain(TerrainRenderer renderer, Vector3 rayOrigin, Vector3 rayDir, float maxDistance, out TerrainRenderer.TerrainChunkInfo info) => _terrainQuery.TryRaycastTerrain(renderer, rayOrigin, rayDir, maxDistance, out info);
    bool IViewerAppHost.TryRaycastTerrain(TerrainRenderer renderer, Vector3 rayOrigin, Vector3 rayDir, float maxDistance, out TerrainRenderer.TerrainChunkInfo info, out Vector3 hitPoint) => _terrainQuery.TryRaycastTerrain(renderer, rayOrigin, rayDir, maxDistance, out info, out hitPoint);
    bool IViewerAppHost.TryResolveHoveredWlLiquidBody(HoveredAssetInfo hoveredInfo, out WlLiquidBody? body) => _investigation.TryResolveHoveredWlLiquidBody(hoveredInfo, out body);
    ref FixedBottomDrawerTab IViewerAppHost.ActiveBottomDrawerTab => ref _activeBottomDrawerTab;
    ref float IViewerAppHost.BottomDrawerHeight => ref _bottomDrawerHeight;
    ref Vector2 IViewerAppHost.DockspaceHostPosition => ref _dockspaceHostPosition;
    ref Vector2 IViewerAppHost.DockspaceHostSize => ref _dockspaceHostSize;
    ref bool IViewerAppHost.ForceApplyShellPanelLayout => ref _forceApplyShellPanelLayout;
    ref bool IViewerAppHost.FullscreenMinimap => ref _fullscreenMinimap;
    ref bool IViewerAppHost.HideUiChrome => ref _hideUiChrome;
    ref ImGuiController IViewerAppHost.ImGui => ref _imGui;
    ref float IViewerAppHost.LeftSidebarWidth => ref _leftSidebarWidth;
    ref string IViewerAppHost.ModelInfo => ref _modelInfo;
    ref ShellPanelId? IViewerAppHost.PendingFocusedShellPanel => ref _pendingFocusedShellPanel;
    ref FixedBottomDrawerTab? IViewerAppHost.PendingRightSidebarSection => ref _pendingRightSidebarSection;
    HashSet<ShellPanelId> IViewerAppHost.PendingShellPanelLayoutRestore => _pendingShellPanelLayoutRestore;
    ref float IViewerAppHost.RightSidebarWidth => ref _rightSidebarWidth;
    Dictionary<ShellPanelId, SavedShellPanelLayout> IViewerAppHost.SavedShellPanelLayouts => _savedShellPanelLayouts;
    ref bool IViewerAppHost.ShowLeftSidebar => ref _showLeftSidebar;
    ref bool IViewerAppHost.ShowMinimapWindow => ref _showMinimapWindow;
    ref bool IViewerAppHost.ShowModelInfo => ref _showModelInfo;
    ref bool IViewerAppHost.ShowRightSidebar => ref _showRightSidebar;
    ref bool IViewerAppHost.ShowWorkspaceBarsPanel => ref _showWorkspaceBarsPanel;
    ref bool IViewerAppHost.UseDockspaceUi => ref _useDockspaceUi;
    ref bool IViewerAppHost.UseTabUi => ref _useTabUi;
    ref IWindow IViewerAppHost.Window => ref _window;
    float IViewerAppHost.ClampFixedSidebarWidth(float width, bool isLeftSidebar, float displayWidth) => _viewerChrome.ClampFixedSidebarWidth(width, isLeftSidebar, displayWidth);
    float IViewerAppHost.GetTopChromeHeight() => GetTopChromeHeight();
    void IViewerAppHost.SetEditorWorkspaceTask(EditorWorkspaceTask task) => _workspaces.SetEditorWorkspaceTask(task);
    ref List<MapDefinition> IViewerAppHost.DiscoveredMaps => ref _discoveredMaps;
    ref Vector3? IViewerAppHost.PendingWorldSpawnOverride => ref _pendingWorldSpawnOverride;
    ref MapDefinition? IViewerAppHost.SelectedMapForPreview => ref _selectedMapForPreview;
    ref Vector2? IViewerAppHost.SelectedSpawnTile => ref _selectedSpawnTile;
    ref bool IViewerAppHost.ShowWdlPreview => ref _showWdlPreview;
    ref WdlPreviewRenderer? IViewerAppHost.WdlPreviewRenderer => ref _wdlPreviewRenderer;
    void IViewerAppHost.LoadFileFromDataSource(string virtualPath) => _modelLoader.LoadFileFromDataSource(virtualPath);
    void IViewerAppHost.LoadMapAtDefaultSpawn(MapDefinition map) => _worldLoader.LoadMapAtDefaultSpawn(map);
    string? IViewerAppHost.ResolveMapWdtPath(string mapDirectory) => _worldLoader.ResolveMapWdtPath(mapDirectory);
    ref AreaTableService? IViewerAppHost.AreaTableService => ref _areaTableService;
    ref WowViewer.Core.World.AreaLookupResult? IViewerAppHost.CurrentAreaLookup => ref _currentAreaLookup;
    ref string IViewerAppHost.CurrentAreaName => ref _currentAreaName;
    ref ISceneRenderer? IViewerAppHost.Renderer => ref _renderer;
    HashSet<string> IViewerAppHost.ReportedAreaDiagnostics => _reportedAreaDiagnostics;
    ref bool IViewerAppHost.AutoFrameModelOnLoad => ref _autoFrameModelOnLoad;
    ref string? IViewerAppHost.DbcBuild => ref _dbcBuild;
    ref float IViewerAppHost.LastWorldSceneCameraPitch => ref _lastWorldSceneCameraPitch;
    ref Vector3 IViewerAppHost.LastWorldSceneCameraPosition => ref _lastWorldSceneCameraPosition;
    ref float IViewerAppHost.LastWorldSceneCameraYaw => ref _lastWorldSceneCameraYaw;
    ref string? IViewerAppHost.LastWorldSceneWdtPath => ref _lastWorldSceneWdtPath;
    ref string? IViewerAppHost.LoadedFileName => ref _loadedFileName;
    ref M2StaticRenderModel? IViewerAppHost.LoadedM2Runtime => ref _loadedM2Runtime;
    ref MdxFile? IViewerAppHost.LoadedMdx => ref _loadedMdx;
    ref WmoV14ToV17Converter.WmoV14Data? IViewerAppHost.LoadedWmo => ref _loadedWmo;
    ref Rendering.LoadingScreen? IViewerAppHost.LoadingScreen => ref _loadingScreen;
    HashSet<string> IViewerAppHost.LoggedStandaloneMissingSkinPaths => _loggedStandaloneMissingSkinPaths;
    SqlSpawnStreamingService IViewerAppHost.SqlSpawnStreaming => _sqlSpawnStreaming;
    Dictionary<string, string?> IViewerAppHost.StandaloneSkinPathCache => _standaloneSkinPathCache;
    ref ReplaceableTextureResolver? IViewerAppHost.TexResolver => ref _texResolver;
    WdlPreviewService IViewerAppHost.WdlPreview => _wdlPreview;
    void IViewerAppHost.FrameCurrentModel() => _modelInspector.FrameCurrentModel();
    string? IViewerAppHost.TryGetLoadedLocalWdtPath() => _dataSourceSession.TryGetLoadedLocalWdtPath();
    ref DBCD.Providers.IDBCProvider? IViewerAppHost.DbcProvider => ref _dbcProvider;
    ref string? IViewerAppHost.DbdDir => ref _dbdDir;
    ref float IViewerAppHost.DefaultFogEnd => ref _renderQuality._defaultFogEnd;
    ref float IViewerAppHost.DefaultFogStart => ref _renderQuality._defaultFogStart;
    ref MinimapRenderer? IViewerAppHost.MinimapRenderer => ref _minimapRenderer;
    StandaloneModelLoaderService IViewerAppHost.ModelLoader => _modelLoader;
    ref int IViewerAppHost.SavedDetailedAdtTileCountOverride => ref _savedDetailedAdtTileCountOverride;
    Dictionary<string, SavedObjectPathFilterMap> IViewerAppHost.SavedObjectPathFiltersByMap => _savedObjectPathFiltersByMap;
    List<TerrainHiddenTileCandidate> IViewerAppHost.TerrainAnalysisHiddenCandidates => _terrainAnalysisHiddenCandidates;
    ref int IViewerAppHost.TerrainAnalysisHiddenSelectedIndex => ref _terrainAnalysisHiddenSelectedIndex;
    ref string IViewerAppHost.TerrainAnalysisHiddenStatus => ref _terrainAnalysisHiddenStatus;
    ref (int tileX, int tileY)? IViewerAppHost.TerrainAnalysisPreviewCompareTile => ref _terrainAnalysisPreviewCompareTile;
    ref float? IViewerAppHost.TerrainAnalysisPreviewSimilarity => ref _terrainAnalysisPreviewSimilarity;
    void IViewerAppHost.ApplyLayoutObjectPreviewModeToScene() => ApplyLayoutObjectPreviewModeToScene();
    void IViewerAppHost.ApplySavedPm4AlignmentToScene() => _pm4Workbench.ApplySavedPm4AlignmentToScene();
    void IViewerAppHost.InvalidatePm4DerivedReports() => _pm4Workbench.InvalidatePm4DerivedReports();
    bool IViewerAppHost.FullLoadMode { get => FullLoadMode; set => FullLoadMode = value; }
    ref bool IViewerAppHost.AutoOpenWorldMapsPanel => ref _autoOpenWorldMapsPanel;
    ref AssetCatalogView? IViewerAppHost.CatalogView => ref _catalogView;
    ref string IViewerAppHost.ExtensionFilter => ref _extensionFilter;
    ref List<string> IViewerAppHost.FilteredFiles => ref _filteredFiles;
    ref string IViewerAppHost.LastGameFolderPath => ref _lastGameFolderPath;
    ref string IViewerAppHost.LastLooseOverlayPath => ref _lastLooseOverlayPath;
    ref string IViewerAppHost.SearchFilter => ref _searchFilter;
    ref int IViewerAppHost.SelectedFileIndex => ref _selectedFileIndex;
    WorldLoaderService IViewerAppHost.WorldLoader => _worldLoader;
    M2CameraPathDocument IViewerAppHost.CameraPath => _cameraPaths._cameraPath;
    ref Terrain.BoundingBoxRenderer? IViewerAppHost.EditorOverlayBb => ref _editorOverlayBb;
    ref int IViewerAppHost.LastMcnkOverlayChunkCount => ref _investigation._lastMcnkOverlayChunkCount;
    ref int IViewerAppHost.LastMcnkWeakCornerCount => ref _investigation._lastMcnkWeakCornerCount;
    ref InvestigationService.McnkOverlayFlags IViewerAppHost.McnkOverlayFlags => ref _investigation._mcnkOverlayFlags;
    ShellLayoutService IViewerAppHost.ShellLayout => _shellLayout;
    ref bool IViewerAppHost.ShowCameraPathOverlay => ref _cameraPaths._showCameraPathOverlay;
    ref bool IViewerAppHost.ShowMcnkFlagOverlay => ref _investigation._showMcnkFlagOverlay;
    ref bool IViewerAppHost.ShowMcnkWeakCorners => ref _investigation._showMcnkWeakCorners;
    DataSourceSessionService IViewerAppHost.DataSourceSession => _dataSourceSession;
    Dictionary<(int tileX, int tileY), WowViewer.Core.Runtime.World.Terrain.Stratigraphy.StratigraphyTileAnalysis> IViewerAppHost.StratigraphyTileAnalyses => _stratigraphyTileAnalyses;
    ConverterDialogsService IViewerAppHost.ConverterDialogs => _converterDialogs;
    PlacementEditService IViewerAppHost.PlacementEditing => _placementEditing;
    ref bool IViewerAppHost.TaxiRideCameraEnabled => ref _captureAutomation._taxiRideCameraEnabled;
    ref bool IViewerAppHost.WlLayerListIsolationEnabled => ref _wlLayerListIsolationEnabled;
    ref string IViewerAppHost.WlLayerSelectedBodyKey => ref _wlLayerSelectedBodyKey;
    void IViewerAppHost.DrawTerrainChunkInvestigationPanel(bool defaultOpen) => _investigation.DrawTerrainChunkInvestigationPanel(defaultOpen);
    void IViewerAppHost.DrawVisualInvestigationToolbox(bool showWorldObjectRangeControls) => _investigation.DrawVisualInvestigationToolbox(showWorldObjectRangeControls);
    void IViewerAppHost.OpenPm4Workbench(Pm4WorkbenchTab tab) => _pm4Workbench.OpenPm4Workbench(tab);
    bool IViewerAppHost.ShouldIncludeWlBodyInUiList(WlLiquidBody body) => _investigation.ShouldIncludeWlBodyInUiList(body);
    bool IViewerAppHost.IsWlListIsolationActive => _investigation.IsWlListIsolationActive;
    ref int IViewerAppHost.ActiveBottomTabIndex => ref _activeBottomTabIndex;
    ref string IViewerAppHost.ActiveDatasetVersionRoot => ref _datasetCatalog._activeDatasetVersionRoot;
    ref WorkbenchTab IViewerAppHost.ActiveTopTab => ref _activeTopTab;
    ref int IViewerAppHost.ActiveUtilitiesTabIndex => ref _activeUtilitiesTabIndex;
    ref bool IViewerAppHost.ArcheologyApplyToNextCapture => ref _archeologyApplyToNextCapture;
    ref bool IViewerAppHost.ArcheologyApplyToVideoRecording => ref _archeologyApplyToVideoRecording;
    ref int IViewerAppHost.ArcheologyMaxUniqueId => ref _archeologyMaxUniqueId;
    ref int IViewerAppHost.ArcheologyMinUniqueId => ref _archeologyMinUniqueId;
    ref bool IViewerAppHost.ArcheologyPlaybackLoop => ref _archeologyPlaybackLoop;
    ref float IViewerAppHost.ArcheologyPlaybackSpeed => ref _archeologyPlaybackSpeed;
    ref int IViewerAppHost.ArcheologyScopeIndex => ref _archeologyScopeIndex;
    ref float IViewerAppHost.CameraSpeed => ref _cameraSpeed;
    ref string IViewerAppHost.CaptureOutputDir => ref _captureAutomation._captureOutputDir;
    List<WoWViewer.Terrain.ClientBuildOption> IViewerAppHost.ClientBuildOptions => _clientBuildOptions;
    ref string IViewerAppHost.DatasetCatalogRoot => ref _datasetCatalog._datasetCatalogRoot;
    ref bool IViewerAppHost.EnableMultisample => ref _renderQuality._enableMultisample;
    ref bool IViewerAppHost.EnableTerrainBackfaceCulling => ref _renderQuality._enableTerrainBackfaceCulling;
    ref bool IViewerAppHost.HasExplicitWmoMliqRotationOverride => ref _hasExplicitWmoMliqRotationOverride;
    ref List<KnownGoodClientPath> IViewerAppHost.KnownGoodClientPaths => ref _knownGoodClientPaths;
    ref Vector2 IViewerAppHost.MinimapPanOffset => ref _minimapPanOffset;
    ref float IViewerAppHost.MinimapZoom => ref _minimapZoom;
    ref bool IViewerAppHost.OpenForgetKnownGoodClientConfirm => ref _openForgetKnownGoodClientConfirm;
    ref string? IViewerAppHost.PendingForgetKnownGoodClientDisplayName => ref _pendingForgetKnownGoodClientDisplayName;
    ref string? IViewerAppHost.PendingForgetKnownGoodClientPath => ref _pendingForgetKnownGoodClientPath;
    ref Vector3 IViewerAppHost.Pm4SavedOverlayRotationDegrees => ref _pm4SavedOverlayRotationDegrees;
    ref Vector3 IViewerAppHost.Pm4SavedOverlayScale => ref _pm4SavedOverlayScale;
    ref Vector3 IViewerAppHost.Pm4SavedOverlayTranslation => ref _pm4SavedOverlayTranslation;
    ref Dictionary<string, Pm4WmoMatchEntry> IViewerAppHost.Pm4WmoMatchEntries => ref _pm4WmoMatchEntries;
    ref Pm4WmoMatchStore? IViewerAppHost.Pm4WmoMatchStore => ref _pm4WmoMatchStore;
    Dictionary<string, SavedPm4ObjectMatchSelection> IViewerAppHost.SavedPm4ObjectMatches => _savedPm4ObjectMatches;
    ref int IViewerAppHost.SelectedBuildOptionIndex => ref _selectedBuildOptionIndex;
    ref string IViewerAppHost.SelectedDatasetVersionRoot => ref _datasetCatalog._selectedDatasetVersionRoot;
    ref TextureFilteringMode IViewerAppHost.TextureFilteringMode => ref _renderQuality._textureFilteringMode;
    ref float IViewerAppHost.UiFontScale => ref _uiFontScale;
    ref ThemesService.UiThemeKind IViewerAppHost.UiTheme => ref _themes._uiTheme;
    ref int IViewerAppHost.VideoCaptureContainerIndex => ref _captureAutomation._videoCaptureContainerIndex;
    ref int IViewerAppHost.VideoCaptureFps => ref _captureAutomation._videoCaptureFps;
    ref bool IViewerAppHost.VideoCaptureIncludeUi => ref _captureAutomation._videoCaptureIncludeUi;
    ref string IViewerAppHost.VideoEncoderExecutable => ref _captureAutomation._videoEncoderExecutable;
    int IViewerAppHost.FindBuildOptionIndex(string? buildVersion) => _clientDialogs.FindBuildOptionIndex(buildVersion);
    void IViewerAppHost.NormalizeWorkbenchStateAfterLoad() => _workbenchPanels.NormalizeWorkbenchStateAfterLoad();
    void IViewerAppHost.RefreshClientBuildOptions() => _clientDialogs.RefreshClientBuildOptions();
    void IViewerAppHost.RefreshDatasetCatalog() => _datasetCatalog.RefreshDatasetCatalog();
    ProjectOutputService IViewerAppHost.ProjectOutput => _projectOutput;
    ref string IViewerAppHost.FolderInputBuf => ref _folderInputBuf;
    ref bool IViewerAppHost.PendingKnownGoodClientAttachLooseFolder => ref _pendingKnownGoodClientAttachLooseFolder;
    ref string? IViewerAppHost.PendingKnownGoodClientBuildVersion => ref _pendingKnownGoodClientBuildVersion;
    ref string? IViewerAppHost.PendingKnownGoodClientPath => ref _pendingKnownGoodClientPath;
    ViewerSettingsService IViewerAppHost.Settings => _settings;
    ref bool IViewerAppHost.ShowBuildSelectionDialog => ref _showBuildSelectionDialog;
    ref bool IViewerAppHost.ShowFolderInput => ref _showFolderInput;
    ref bool IViewerAppHost.ShowListfileInput => ref _showListfileInput;
    ref bool IViewerAppHost.ShowRosettaDatastoreDialog => ref _showRosettaDatastoreDialog;
    CascAhdrSourceService IViewerAppHost.CascAhdrSource => _cascAhdrSource;
    ClientDialogsService IViewerAppHost.ClientDialogs => _clientDialogs;
    ref bool IViewerAppHost.ShowFileBrowser => ref _showFileBrowser;
    ref bool IViewerAppHost.ShowLogViewer => ref _showLogViewer;
    ref bool IViewerAppHost.ShowPerfWindow => ref _showPerfWindow;
    ref bool IViewerAppHost.ShowSynthesizedMinimapExportDialog => ref _showSynthesizedMinimapExportDialog;
    ref bool IViewerAppHost.WantExportGlb => ref _wantExportGlb;
    ref bool IViewerAppHost.WantExportGlbCollision => ref _wantExportGlbCollision;
    ref bool IViewerAppHost.WantExportMapGlbTiles => ref _wantExportMapGlbTiles;
    ref bool IViewerAppHost.WantOpenFile => ref _wantOpenFile;
    ref bool IViewerAppHost.WantTerrainExport => ref _wantTerrainExport;
    ref bool IViewerAppHost.WantTerrainImport => ref _wantTerrainImport;
    ref bool IViewerAppHost.WorkbenchOpen => ref _workbenchOpen;
    void IViewerAppHost.ResetCamera() => ResetCamera();
    ref int IViewerAppHost.ActivePm4TabIndex => ref _activePm4TabIndex;
    void IViewerAppHost.CopyTextToClipboard(string text, string description) => _navigatorPanel.CopyTextToClipboard(text, description);
    ref bool IViewerAppHost.ArcheologyPlaybackActive => ref _archeologyPlaybackActive;
    ref MapListSortMode IViewerAppHost.MapListSortMode => ref _mapListSortMode;
    Pm4WorkbenchService IViewerAppHost.Pm4Workbench => _pm4Workbench;
    ref bool IViewerAppHost.ShowUniqueIdArchaeologyWindow => ref _showUniqueIdArchaeologyWindow;
    HashSet<int> IViewerAppHost.HighlightedStandaloneWmoGroupIndices => _highlightedStandaloneWmoGroupIndices;
    ref int IViewerAppHost.HoveredStandaloneWmoGroupIndex => ref _hoveredStandaloneWmoGroupIndex;
    ref int IViewerAppHost.SelectedStandaloneWmoGroupIndex => ref _selectedStandaloneWmoGroupIndex;
    ref bool IViewerAppHost.StandaloneWmoGroupLabelsAllEnabled => ref _standaloneWmoGroupLabelsAllEnabled;
    ref bool IViewerAppHost.StandaloneWmoGroupOverlayEnabled => ref _standaloneWmoGroupOverlayEnabled;
    ref bool IViewerAppHost.StandaloneWmoOverlayIncludeHiddenGroups => ref _standaloneWmoOverlayIncludeHiddenGroups;
    void IViewerAppHost.DrawAssetPathActions(string label, string assetPath, string idSuffix) => _navigatorPanel.DrawAssetPathActions(label, assetPath, idSuffix);
    void IViewerAppHost.FramePoint(Vector3 target, float radius) => _navigatorPanel.FramePoint(target, radius);
    ChunkEditService IViewerAppHost.ChunkEdit => _chunkEdit;
    ref bool IViewerAppHost.LayoutObjectPreviewMode => ref _layoutObjectPreviewMode;
    ref bool IViewerAppHost.ShowWeakSignalWindow => ref _showWeakSignalWindow;
    StratigraphyService IViewerAppHost.Stratigraphy => _stratigraphy;
    ref int IViewerAppHost.PendingMinimapTeleportClickCount => ref _pendingMinimapTeleportClickCount;
    ref (int tileX, int tileY)? IViewerAppHost.PendingMinimapTeleportTile => ref _pendingMinimapTeleportTile;
    ModelInspectorPanelService IViewerAppHost.ModelInspector => _modelInspector;
    TerrainControlsPanelService IViewerAppHost.TerrainControlsPanel => _terrainControlsPanel;
    TerrainQueryService IViewerAppHost.TerrainQuery => _terrainQuery;
    NavigatorPanelService IViewerAppHost.NavigatorPanel => _navigatorPanel;
    InvestigationService IViewerAppHost.Investigation => _investigation;
    TerrainInspectionPanelService IViewerAppHost.TerrainInspection => _terrainInspection;
    ArchaeologyPanelService IViewerAppHost.ArchaeologyPanel => _archaeologyPanel;
    AudioPanelService IViewerAppHost.AudioPanel => _audioPanel;
    InspectorPayloadsService IViewerAppHost.InspectorPayloads => _inspectorPayloads;
    LightingPanelService IViewerAppHost.LightingPanel => _lightingPanel;
    MainMenuBarService IViewerAppHost.MainMenuBar => _mainMenuBar;
    TaxiPanelService IViewerAppHost.TaxiPanel => _taxiPanel;
    ThemesService IViewerAppHost.Themes => _themes;
    ViewerChromeService IViewerAppHost.ViewerChrome => _viewerChrome;
    WorldObjectsPanelService IViewerAppHost.WorldObjectsPanel => _worldObjectsPanel;
    ref CameraHudRig? IViewerAppHost.CameraHudRig => ref _cameraHudRig;
    DatasetCatalogService IViewerAppHost.DatasetCatalog => _datasetCatalog;
    RenderQualityService IViewerAppHost.RenderQuality => _renderQuality;
    ref TerrainAnalysisPreviewTexture? IViewerAppHost.TerrainAnalysisAlphaTexture => ref _terrainAnalysisAlphaTexture;
    ref TerrainAnalysisPreviewTexture? IViewerAppHost.TerrainAnalysisGlobalTexture => ref _terrainAnalysisGlobalTexture;
    ref TerrainAnalysisPreviewTexture? IViewerAppHost.TerrainAnalysisLocalTexture => ref _terrainAnalysisLocalTexture;
    ref double IViewerAppHost.CurrentFps => ref _currentFps;
    DatasetExportDialogsService IViewerAppHost.DatasetExportDialogs => _datasetExportDialogs;
    ref bool IViewerAppHost.ShowCameraPathWindow => ref _showCameraPathWindow;
    ref bool IViewerAppHost.ShowCaptureAutomationWindow => ref _showCaptureAutomationWindow;
    WorkbenchPanelsService IViewerAppHost.WorkbenchPanels => _workbenchPanels;
    CameraPathsService IViewerAppHost.CameraPaths => _cameraPaths;
    StartupAutomationService IViewerAppHost.StartupAutomation => _startupAutomation;
    CaptureAutomationService IViewerAppHost.CaptureAutomation => _captureAutomation;
    SettingsWindowService IViewerAppHost.SettingsWindow => _settingsWindow;
    SynthesizedMinimapExportService IViewerAppHost.SynthesizedMinimapExport => _synthesizedMinimapExport;
    WorkspacesService IViewerAppHost.Workspaces => _workspaces;
    void IViewerAppHost.OpenCapturePanelTab(CameraPathsService.CapturePanelTab tab) => _cameraPaths.OpenCapturePanelTab(tab);
    void IViewerAppHost.DrawCapturePanelContent() => _cameraPaths.DrawCapturePanelContent();
    void IViewerAppHost.StopCameraPathPlayback() => _cameraPaths.StopCameraPathPlayback();
    List<CaptureAutomationService.CameraShotPoint> IViewerAppHost.CameraShotPoints => _captureAutomation._cameraShotPoints;
    Queue<CaptureAutomationService.PendingCaptureRequest> IViewerAppHost.CaptureQueue => _captureAutomation._captureQueue;
    ref CaptureAutomationService.PendingCaptureRequest? IViewerAppHost.ActiveCaptureRequest => ref _captureAutomation._activeCaptureRequest;
    ref int IViewerAppHost.TaxiRideCameraRouteId => ref _captureAutomation._taxiRideCameraRouteId;
    ref WorldScene? IViewerAppHost.TaxiRideCameraScene => ref _captureAutomation._taxiRideCameraScene;
    ref CaptureAutomationService.TaxiRideCameraMode IViewerAppHost.TaxiRideCameraMode => ref _captureAutomation._taxiRideCameraMode;
    ref float IViewerAppHost.TaxiRideChaseDistance => ref _captureAutomation._taxiRideChaseDistance;
    ref float IViewerAppHost.TaxiRideChaseHeight => ref _captureAutomation._taxiRideChaseHeight;
    ref float IViewerAppHost.TaxiRideCockpitHeight => ref _captureAutomation._taxiRideCockpitHeight;
    ref float IViewerAppHost.TaxiRideFreeLookYawOffset => ref _captureAutomation._taxiRideFreeLookYawOffset;
    ref float IViewerAppHost.TaxiRideFreeLookPitchOffset => ref _captureAutomation._taxiRideFreeLookPitchOffset;
    ref bool IViewerAppHost.TaxiRideCameraPoseInitialized => ref _captureAutomation._taxiRideCameraPoseInitialized;
    ref long IViewerAppHost.LastTaxiRideCameraTick => ref _captureAutomation._lastTaxiRideCameraTick;
    ref CaptureAutomationService.ActiveVideoRecording? IViewerAppHost.ActiveVideoRecording => ref _captureAutomation._activeVideoRecording;
    void IViewerAppHost.DrawCaptureAutomationContent() => _captureAutomation.DrawCaptureAutomationContent();
    void IViewerAppHost.QueueCurrentCameraCapture(bool includeUi, bool exitAfterCapture, int captureAfterFrames, bool allowWindowCloseOnCapture) => _captureAutomation.QueueCurrentCameraCapture(includeUi, exitAfterCapture, captureAfterFrames, allowWindowCloseOnCapture);
    void IViewerAppHost.EnqueueShotCapture(CaptureAutomationService.CameraShotPoint shot, bool includeUi, bool exitAfterCapture, CaptureAutomationService.CaptureQueueOptions? options) => _captureAutomation.EnqueueShotCapture(shot, includeUi, exitAfterCapture, options);
    void IViewerAppHost.EnqueueShotCapture(CaptureAutomationService.CameraShotPoint shot, bool includeUi, bool exitAfterCapture) => _captureAutomation.EnqueueShotCapture(shot, includeUi, exitAfterCapture);
    void IViewerAppHost.GenerateMkHarvestViewerValidationObjectArtifacts(string datasetRoot, string withObjectsOutputDirectory, string noObjectsOutputDirectory, string objectsOnlyOutputDirectory) => _captureAutomation.GenerateMkHarvestViewerValidationObjectArtifacts(datasetRoot, withObjectsOutputDirectory, noObjectsOutputDirectory, objectsOnlyOutputDirectory);
    bool IViewerAppHost.TryStartCurrentViewVideoRecording(bool includeUi, string? label) => _captureAutomation.TryStartCurrentViewVideoRecording(includeUi, label);
    void IViewerAppHost.StopVideoRecording(string? statusOverride) => _captureAutomation.StopVideoRecording(statusOverride);
    void IViewerAppHost.StopTaxiRideCamera(string? statusMessage) => _captureAutomation.StopTaxiRideCamera(statusMessage);
    string IViewerAppHost.GetCurrentCaptureMapName() => _captureAutomation.GetCurrentCaptureMapName();
    string IViewerAppHost.GetCurrentCaptureBuildVersion() => _captureAutomation.GetCurrentCaptureBuildVersion();
    ref bool IViewerAppHost.WantSelectDatasetCatalogRoot => ref _datasetCatalog._wantSelectDatasetCatalogRoot;
    ref EditorHost? IViewerAppHost.EditorHost => ref _editorHost;
    ref EditorSession? IViewerAppHost.EditorSession => ref _editorSession;
    Workbench.Pages.EditorWorkbenchPages IViewerAppHost.EnsureEditorPages() => EnsureEditorPages();
    void IViewerAppHost.EnsureEditorHost() => EnsureEditorHost();
    void IViewerAppHost.DrawVisualInvestigationModeButton(InvestigationService.VisualInvestigationMode mode, string label, string tooltip) => _investigation.DrawVisualInvestigationModeButton(mode, label, tooltip);
    void IViewerAppHost.DrawLogViewerContent() => _logViewer.DrawLogViewerContent();
    bool IViewerAppHost.TryGetActiveMinimapState(out List<(int tx, int ty)>? existingTiles, out Func<int, int, bool>? isTileLoaded, out int loadedTileCount, out string? mapName) => _minimapAndStatus.TryGetActiveMinimapState(out existingTiles, out isTileLoaded, out loadedTileCount, out mapName);
    void IViewerAppHost.FocusCameraOnLitLight(int lightIndex, bool closeFullscreenAfterFocus) => _minimapAndStatus.FocusCameraOnLitLight(lightIndex, closeFullscreenAfterFocus);
    void IViewerAppHost.DrawInteractiveMinimapSurface(string interactionId, Vector2 cursorPos, float mapSize, List<(int tx, int ty)> existingTiles, Func<int, int, bool> isTileLoaded, string? mapName, MinimapAndStatusService.MinimapTeleportMode teleportMode, out float viewMinTx, out float viewMinTy, out float cellSize) => _minimapAndStatus.DrawInteractiveMinimapSurface(interactionId, cursorPos, mapSize, existingTiles, isTileLoaded, mapName, teleportMode, out viewMinTx, out viewMinTy, out cellSize);
    void IViewerAppHost.ClampMinimapPanOffset() => _minimapAndStatus.ClampMinimapPanOffset();
    void IViewerAppHost.ToggleFullscreenMinimap() => _minimapAndStatus.ToggleFullscreenMinimap();
    void IViewerAppHost.DrawMinimapContent(int loadedTileCount, string? mapName, List<(int tx, int ty)> existingTiles, Func<int, int, bool> isTileLoaded) => _minimapAndStatus.DrawMinimapContent(loadedTileCount, mapName, existingTiles, isTileLoaded);
    void IViewerAppHost.DrawMapSortModeSelector(string id) => DrawMapSortModeSelector(id);
    void IViewerAppHost.DrawRenderQualityContent() => _renderQuality.DrawRenderQualityContent();
    ref bool IViewerAppHost.ShowSettingsWindow => ref _settingsWindow._showSettingsWindow;
    void IViewerAppHost.DrawAuthoritativeFogControls(bool showDescription) => _settingsWindow.DrawAuthoritativeFogControls(showDescription);
    void IViewerAppHost.DrawWorkspaceBarsPanelContent() => _viewerChrome.DrawWorkspaceBarsPanelContent();
    ref UtilitiesBottomTab? IViewerAppHost.LegacyUtilityPage => ref _legacyUtilityPage;
    void IViewerAppHost.DrawUnifiedInspectorContent() => _workbenchPanels.DrawUnifiedInspectorContent();
    void IViewerAppHost.DrawDockedShellPanelsForLane(ShellPanelLane lane, float sidebarHeight) => _workbenchPanels.DrawDockedShellPanelsForLane(lane, sidebarHeight);
    void IViewerAppHost.DrawFixedSidebarWidthControl(string label, ref float width, bool isLeftSidebar, float displayWidth, string tooltip) => _viewerChrome.DrawFixedSidebarWidthControl(label, ref width, isLeftSidebar, displayWidth, tooltip);
    void IViewerAppHost.DrawTerrainControlsAdjustmentWeakSignalContent() => _terrainControlsPanel.DrawTerrainControlsAdjustmentWeakSignalContent();
    void IViewerAppHost.DrawTemporalStratigraphySubTab() => _terrainControlsPanel.DrawTemporalStratigraphySubTab();
    void IViewerAppHost.OpenWorkbenchTab(UtilitiesBottomTab tab) => _workbenchPanels.OpenWorkbenchTab(tab);
    void IViewerAppHost.OpenWorkbenchTab(ToolsBottomTab tab) => _workbenchPanels.OpenWorkbenchTab(tab);
    void IViewerAppHost.OpenWorkbenchTab(WorldBottomTab tab) => _workbenchPanels.OpenWorkbenchTab(tab);
    void IViewerAppHost.OpenWorkbenchTab(ModelBottomTab tab) => _workbenchPanels.OpenWorkbenchTab(tab);
    void IViewerAppHost.OpenWorkbenchTab(WorkbenchTab topTab, int bottomIndex) => _workbenchPanels.OpenWorkbenchTab(topTab, bottomIndex);
    void IViewerAppHost.PrepareSynthesizedMinimapExportDialogInputs() => _synthesizedMinimapExport.PrepareSynthesizedMinimapExportDialogInputs();
    void IViewerAppHost.DrawSynthesizedMinimapExportContent(bool showCloseButton) => _synthesizedMinimapExport.DrawSynthesizedMinimapExportContent(showCloseButton);
    void IViewerAppHost.NormalizeStandaloneWmoGroupSelection(WmoRenderer wmoRenderer) => _wmoGroupsPanel.NormalizeStandaloneWmoGroupSelection(wmoRenderer);
    void IViewerAppHost.ToggleStandaloneWmoGroupHighlight(int renderGroupIndex) => _wmoGroupsPanel.ToggleStandaloneWmoGroupHighlight(renderGroupIndex);
    void IViewerAppHost.SetWorkspaceMode(WorkspaceMode mode) => _workspaces.SetWorkspaceMode(mode);
    bool IViewerAppHost.IsEditorTaskAvailable(EditorWorkspaceTask task) => _workspaces.IsEditorTaskAvailable(task);
    string IViewerAppHost.GetWorkspaceTargetSummary() => _workspaces.GetWorkspaceTargetSummary();
    string IViewerAppHost.GetWorkspaceSaveStatusSummary() => _workspaces.GetWorkspaceSaveStatusSummary();
    ViewerKeyContext IViewerAppHost.GetActiveKeyContext() => GetActiveKeyContext();
}
