using System.Text.Json;
using AlphaWdtAnalyzer.Core;

namespace WoWRollback.AnalysisModule;

/// <summary>
/// High-level orchestrator for analysis operations.
/// Coordinates UniqueID analysis, terrain CSV generation, overlay creation, and manifest building.
/// </summary>
public sealed class AnalysisOrchestrator
{
    /// <summary>
    /// Runs complete analysis pipeline on converted ADT files.
    /// </summary>
    /// <param name="adtOutputDir">Directory containing converted LK ADTs</param>
    /// <param name="analysisOutputDir">Output directory for analysis CSVs</param>
    /// <param name="viewerOutputDir">Output directory for viewer overlays</param>
    /// <param name="mapName">Map name</param>
    /// <param name="version">Version string</param>
    /// <param name="opts">Analysis options</param>
    /// <returns>Result containing paths to generated files</returns>
    public AnalysisResult RunAnalysis(
        string adtOutputDir,
        string analysisOutputDir,
        string viewerOutputDir,
        string mapName,
        string version,
        AnalysisOptions opts)
    {
        try
        {
            var uniqueIdCsvs = new List<string>();
            var terrainCsvs = new List<string>();
            var overlayCount = 0;
            var placementCsvs = new List<string>();
            string? manifestPath = null;

            // Try load analysis directory with index.json. If missing, we can still generate terrain/shadow overlays from CSVs.
            var analysisIndexPath = Path.Combine(adtOutputDir, "analysis", "index.json");
            AnalysisIndex? analysisIndex = null;
            if (File.Exists(analysisIndexPath))
            {
                var indexJson = File.ReadAllText(analysisIndexPath);
                analysisIndex = JsonSerializer.Deserialize<AnalysisIndex>(indexJson);
            }

            // Stage 1: UniqueID Analysis (from index.json placements)
            if (opts.GenerateUniqueIdCsvs && analysisIndex != null)
            {
                var uniqueIdDir = Path.Combine(analysisOutputDir, "uniqueids");
                Directory.CreateDirectory(uniqueIdDir);

                var analyzer = new UniqueIdAnalyzer(opts.UniqueIdGapThreshold);
                var uniqueIdResult = analyzer.AnalyzeFromIndex(analysisIndex, mapName, uniqueIdDir);

                if (uniqueIdResult.Success)
                {
                    uniqueIdCsvs.Add(uniqueIdResult.CsvPath);
                    uniqueIdCsvs.Add(uniqueIdResult.LayersJsonPath);
                }
            }

            // Stage 2c: Copy placements CSV from ADT analysis (03_adts/<ver>/analysis/csv/placements.csv)
            var sourcePlacementsCsv = Path.Combine(adtOutputDir, "analysis", "csv", "placements.csv");
            string? copiedPlacementsCsv = null;
            var objectsDirOut = Path.Combine(analysisOutputDir, "objects");
            Directory.CreateDirectory(objectsDirOut);
            if (File.Exists(sourcePlacementsCsv))
            {
                copiedPlacementsCsv = Path.Combine(objectsDirOut, $"{mapName}_placements.csv");
                File.Copy(sourcePlacementsCsv, copiedPlacementsCsv, overwrite: true);
                placementCsvs.Add(copiedPlacementsCsv);
            }

            // Stage 2b: Placements CSV (from analysis index)
            if (analysisIndex != null)
            {
                var objectsDir = Path.Combine(analysisOutputDir, "objects");
                Directory.CreateDirectory(objectsDir);
                var placements = new PlacementsCsvGenerator().Generate(analysisIndex, mapName, objectsDir);
                placementCsvs.Add(placements);

                var masterWriter = new MapMasterIndexWriter();
                var masterDir = Path.Combine(analysisOutputDir, "master");
                Directory.CreateDirectory(masterDir);
                var masterPath = masterWriter.Write(analysisIndex, mapName, version, masterDir);
                placementCsvs.Add(masterPath);
            }

            // Stage 2: Copy Terrain CSVs (already generated by ADT conversion)
            if (opts.GenerateTerrainCsvs)
            {
                var sourceTerrainCsv = Path.Combine(adtOutputDir, "csv", "maps", mapName, "terrain.csv");
                var sourceShadowCsv = Path.Combine(adtOutputDir, "csv", "maps", mapName, "shadow.csv");
                var terrainDir = Path.Combine(analysisOutputDir, "terrain");
                Directory.CreateDirectory(terrainDir);

                if (File.Exists(sourceTerrainCsv))
                {
                    var targetPath = Path.Combine(terrainDir, $"{mapName}_terrain.csv");
                    File.Copy(sourceTerrainCsv, targetPath, overwrite: true);
                    terrainCsvs.Add(targetPath);
                }

                if (File.Exists(sourceShadowCsv))
                {
                    var targetPath = Path.Combine(terrainDir, $"{mapName}_shadow.csv");
                    File.Copy(sourceShadowCsv, targetPath, overwrite: true);
                    terrainCsvs.Add(targetPath);
                }
            }

            // Stage 3: Overlay Generation
            if (opts.GenerateOverlays)
            {
                var overlayGenerator = new OverlayGenerator();

                // 3a. Objects overlays (require analysis index)
                if (analysisIndex != null)
                {
                    var objResult = overlayGenerator.GenerateFromIndex(
                        analysisIndex,
                        viewerOutputDir,
                        mapName,
                        version);
                    if (objResult.Success)
                    {
                        overlayCount += objResult.ObjectOverlays;
                    }
                }

                // 3a-alt. Objects overlays from placements.csv when index is missing
                if (analysisIndex == null && !string.IsNullOrEmpty(copiedPlacementsCsv) && File.Exists(copiedPlacementsCsv))
                {
                    var objFromCsv = overlayGenerator.GenerateObjectsFromPlacementsCsv(
                        copiedPlacementsCsv,
                        viewerOutputDir,
                        mapName,
                        version);
                    if (objFromCsv.Success)
                    {
                        overlayCount += objFromCsv.ObjectOverlays;
                    }
                }

                // 3b. Terrain overlays from terrain.csv
                var terrResult = overlayGenerator.GenerateTerrainOverlaysFromCsv(
                    adtOutputDir,
                    viewerOutputDir,
                    mapName,
                    version);
                if (terrResult.Success)
                {
                    overlayCount += terrResult.TerrainOverlays;
                }

                // 3c. Shadow overlays from shadow.csv
                var shResult = overlayGenerator.GenerateShadowOverlaysFromCsv(
                    adtOutputDir,
                    viewerOutputDir,
                    mapName,
                    version);
                if (shResult.Success)
                {
                    overlayCount += shResult.ShadowOverlays;
                }
            }

            // Stage 3b: UniqueID analysis from placements.csv if index missing
            if (analysisIndex == null && !string.IsNullOrEmpty(copiedPlacementsCsv) && File.Exists(copiedPlacementsCsv))
            {
                var uniqueIdDir = Path.Combine(analysisOutputDir, "uniqueids");
                Directory.CreateDirectory(uniqueIdDir);
                var analyzerFromCsv = new UniqueIdAnalyzer(opts.UniqueIdGapThreshold);
                var uidRes = analyzerFromCsv.AnalyzeFromPlacementsCsv(copiedPlacementsCsv, mapName, uniqueIdDir);
                if (uidRes.Success)
                {
                    uniqueIdCsvs.Add(uidRes.CsvPath);
                    uniqueIdCsvs.Add(uidRes.LayersJsonPath);
                }
            }

            // Stage 4: Manifest Building
            if (opts.GenerateManifest)
            {
                var manifestBuilder = new OverlayManifestBuilder();
                var manifestResult = manifestBuilder.Build(
                    viewerOutputDir,
                    mapName,
                    version);

                if (manifestResult.Success)
                {
                    manifestPath = manifestResult.ManifestPath;
                }
            }

            return new AnalysisResult(
                UniqueIdCsvs: uniqueIdCsvs,
                TerrainCsvs: terrainCsvs,
                PlacementCsvs: placementCsvs,
                OverlayCount: overlayCount,
                ManifestPath: manifestPath,
                Success: true);
        }
        catch (Exception ex)
        {
            return new AnalysisResult(
                UniqueIdCsvs: Array.Empty<string>(),
                TerrainCsvs: Array.Empty<string>(),
                PlacementCsvs: Array.Empty<string>(),
                OverlayCount: 0,
                ManifestPath: null,
                Success: false,
                ErrorMessage: $"Analysis failed: {ex.Message}");
        }
    }
}
