using System.Diagnostics;
using System.Numerics;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using ImGuiNET;
using WowViewer.Core.IO.Mdx;
using WoWViewer.DataSources;
using WoWViewer.Export;
using WoWViewer.Logging;
using WoWViewer.Rendering;
using WoWViewer.Catalog;
using WoWViewer.Capture;
using WoWViewer.Population;
using WoWViewer.Terrain;
using Silk.NET.Input;
using Silk.NET.Maths;
using Silk.NET.OpenGL;
using Silk.NET.OpenGL.Extensions.ImGui;
using Silk.NET.Windowing;
using WowViewer.Core.IO.Files;
using WowViewer.Core.IO.Maps;
using WowViewer.Core.Maps;
using WoWViewer.Terrain.Vlm;
using WowViewer.Core.IO.M2;
using WowViewer.Core.IO.M2Chunked;
using WowViewer.Core.IO.M2Era1121;
using WowViewer.Core.M2;
using WowViewer.Core.Runtime.M2;
using WowViewer.Core.Runtime.Marketing;
using WowViewer.Core.Runtime.World.Visibility;
using ObjectInstance = WowViewer.Core.Runtime.World.WorldObjectInstance;
using WowViewer.Core.IO.Converters;
using WoWViewer.Workbench;
using CoreMdxCollisionSummary = WowViewer.Core.Mdx.MdxCollisionSummary;
using CoreMdxGeometryFile = WowViewer.Core.Mdx.MdxGeometryFile;
using CoreMdxSummary = WowViewer.Core.Mdx.MdxSummary;
using CorePm4DocumentReader = WowViewer.Core.PM4.Services.Pm4ResearchReader;
using Pm4CoordinateService = WowViewer.Core.PM4.Services.Pm4CoordinateService;
using WowViewer.Core.Runtime.World;
using WoWViewer.UI;
using WowViewer.Core.Runtime.World.Minimap;
using System.IO;
using WowViewer.Core.IO.Dbc;
using WowViewer.Core.Runtime.World.Passes;
using static WoWViewer.ViewerApp;
using static WoWViewer.MinimapAndStatusService;

namespace WoWViewer;

// NavigatorPanelService host bridge. Bridged member types are declared across ViewerApp partial files, so this
// file carries those files' using directives; the moved members keep their original usings.
internal sealed partial class NavigatorPanelService
{
    // Host bridge (same names as the former ViewerApp members).
    private ref bool _autoOpenWorldMapsPanel => ref _host.AutoOpenWorldMapsPanel;
    private ref Camera _camera => ref _host.Camera;
    private CascAhdrSourceService _cascAhdrSource => _host.CascAhdrSource;
    private ref string _currentAreaName => ref _host.CurrentAreaName;
    private ref IDataSource? _dataSource => ref _host.DataSource;
    private DataSourceSessionService _dataSourceSession => _host.DataSourceSession;
    private ref List<MapDefinition> _discoveredMaps => ref _host.DiscoveredMaps;
    private ref string _extensionFilter => ref _host.ExtensionFilter;
    private ref List<string> _filteredFiles => ref _host.FilteredFiles;
    private ref bool _fullscreenMinimap => ref _host.FullscreenMinimap;
    private ref float _leftSidebarWidth => ref _host.LeftSidebarWidth;
    private ref string? _loadedFileName => ref _host.LoadedFileName;
    private ref string? _loadedFilePath => ref _host.LoadedFilePath;
    private ref MapListSortMode _mapListSortMode => ref _host.MapListSortMode;
    private ref MinimapRenderer? _minimapRenderer => ref _host.MinimapRenderer;
    private StandaloneModelLoaderService _modelLoader => _host.ModelLoader;
    private ref int _pendingMinimapTeleportClickCount => ref _host.PendingMinimapTeleportClickCount;
    private ref (int tileX, int tileY)? _pendingMinimapTeleportTile => ref _host.PendingMinimapTeleportTile;
    private ref string _searchFilter => ref _host.SearchFilter;
    private ref int _selectedFileIndex => ref _host.SelectedFileIndex;
    private ShellLayoutService _shellLayout => _host.ShellLayout;
    private ref bool _showFileBrowser => ref _host.ShowFileBrowser;
    private ref bool _showLeftSidebar => ref _host.ShowLeftSidebar;
    private ref bool _showMinimapWindow => ref _host.ShowMinimapWindow;
    private ref string _statusMessage => ref _host.StatusMessage;
    private TaxiAndAreaPoiSelectionService _taxiAndAreaPoi => _host.TaxiAndAreaPoi;
    private ref TerrainManager? _terrainManager => ref _host.TerrainManager;
    private ref bool _useDockspaceUi => ref _host.UseDockspaceUi;
    private ref bool _useTabUi => ref _host.UseTabUi;
    private ref VlmTerrainManager? _vlmTerrainManager => ref _host.VlmTerrainManager;
    private WdlPreviewService _wdlPreview => _host.WdlPreview;
    private ref WdlPreviewCacheService? _wdlPreviewCacheService => ref _host.WdlPreviewCacheService;
    private WorldLoaderService _worldLoader => _host.WorldLoader;
    private ref WorldScene? _worldScene => ref _host.WorldScene;
    private float ClampFixedSidebarWidth(float width, bool isLeftSidebar, float displayWidth) => _host.ClampFixedSidebarWidth(width, isLeftSidebar, displayWidth);
    private void ClampMinimapPanOffset() => _host.ClampMinimapPanOffset();
    private void ClearSelectedWlLiquidBody(bool clearListIsolation) => _host.ClearSelectedWlLiquidBody(clearListIsolation);
    private void DrawDockedShellPanelsForLane(ShellPanelLane lane, float sidebarHeight) => _host.DrawDockedShellPanelsForLane(lane, sidebarHeight);
    private void DrawFixedSidebarWidthControl(string label, ref float width, bool isLeftSidebar, float displayWidth, string tooltip) => _host.DrawFixedSidebarWidthControl(label, ref width, isLeftSidebar, displayWidth, tooltip);
    private void DrawInteractiveMinimapSurface(string interactionId, Vector2 cursorPos, float mapSize, List<(int tx, int ty)> existingTiles, Func<int, int, bool> isTileLoaded, string? mapName, MinimapTeleportMode teleportMode, out float viewMinTx, out float viewMinTy, out float cellSize) => _host.DrawInteractiveMinimapSurface(interactionId, cursorPos, mapSize, existingTiles, isTileLoaded, mapName, teleportMode, out viewMinTx, out viewMinTy, out cellSize);
    private void DrawMapSortModeSelector(string id) => _host.DrawMapSortModeSelector(id);
    private void DrawWorkspaceBarsPanelContent() => _host.DrawWorkspaceBarsPanelContent();
    private float GetTopChromeHeight() => _host.GetTopChromeHeight();
    private void RefreshSelectedWorldObjectInfo() => _host.RefreshSelectedWorldObjectInfo();
    private void ToggleFullscreenMinimap() => _host.ToggleFullscreenMinimap();
    private bool TryGetActiveMinimapState(out List<(int tx, int ty)>? existingTiles, out Func<int, int, bool>? isTileLoaded, out int loadedTileCount, out string? mapName) => _host.TryGetActiveMinimapState(out existingTiles, out isTileLoaded, out loadedTileCount, out mapName);
}
