using System.Numerics;
using ImGuiNET;
using WoWViewer.Rendering;
using WoWViewer.Terrain;
using WoWViewer.Workbench;
using System.Diagnostics;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using WowViewer.Core.IO.Mdx;
using WoWViewer.DataSources;
using WoWViewer.Export;
using WoWViewer.Logging;
using WoWViewer.Catalog;
using WoWViewer.Capture;
using WoWViewer.Population;
using Silk.NET.Input;
using Silk.NET.Maths;
using Silk.NET.OpenGL;
using Silk.NET.OpenGL.Extensions.ImGui;
using Silk.NET.Windowing;
using WowViewer.Core.IO.Files;
using WowViewer.Core.IO.Maps;
using WowViewer.Core.Maps;
using WoWViewer.Terrain.Vlm;
using WowViewer.Core.IO.M2;
using WowViewer.Core.IO.M2Chunked;
using WowViewer.Core.IO.M2Era1121;
using WowViewer.Core.M2;
using WowViewer.Core.Runtime.M2;
using WowViewer.Core.Runtime.Marketing;
using WowViewer.Core.Runtime.World.Visibility;
using ObjectInstance = WowViewer.Core.Runtime.World.WorldObjectInstance;
using WowViewer.Core.IO.Converters;
using CoreMdxCollisionSummary = WowViewer.Core.Mdx.MdxCollisionSummary;
using CoreMdxGeometryFile = WowViewer.Core.Mdx.MdxGeometryFile;
using CoreMdxSummary = WowViewer.Core.Mdx.MdxSummary;
using CorePm4DocumentReader = WowViewer.Core.PM4.Services.Pm4ResearchReader;
using Pm4CoordinateService = WowViewer.Core.PM4.Services.Pm4CoordinateService;
using WowViewer.Core.Editor;
using WowViewer.Core.Editor.Bridge;
using WowViewer.Core.Editor.Eras;
using WowViewer.Core.Editor.Logging;
using WowViewer.Core.Editor.Operations;
using WowViewer.Core.Editor.Plugins;
using WowViewer.Core.Editor.Session;
using WowViewer.Core.PM4.Matching;
using WowViewer.Core.PM4.Reconciliation;
using WowViewer.Core.PM4.Services;
using WowViewer.Core.IO.Terrain;
using static WoWViewer.ViewerApp;

namespace WoWViewer;

// WorkspacesService host bridge. Bridged member types are declared across ViewerApp partial files, so this
// file carries those files' using directives; the moved members keep their original usings.
internal sealed partial class WorkspacesService
{
    // Host bridge (same names as the former ViewerApp members).
    private ref FixedBottomDrawerTab _activeBottomDrawerTab => ref _host.ActiveBottomDrawerTab;
    private ref WorkbenchTab _activeTopTab => ref _host.ActiveTopTab;
    private ref Camera _camera => ref _host.Camera;
    private CameraPathsService _cameraPaths => _host.CameraPaths;
    private ref float _cameraSpeed => ref _host.CameraSpeed;
    private CaptureAutomationService _captureAutomation => _host.CaptureAutomation;
    private ChunkEditService _chunkEdit => _host.ChunkEdit;
    private ref IDataSource? _dataSource => ref _host.DataSource;
    private ref EditorWorkspaceTask _editorWorkspaceTask => ref _host.EditorWorkspaceTask;
    private ref float _fovDegrees => ref _host.FovDegrees;
    private InvestigationService _investigation => _host.Investigation;
    private ref string? _loadedFileName => ref _host.LoadedFileName;
    private ref string _modelInfo => ref _host.ModelInfo;
    private ModelInspectorPanelService _modelInspector => _host.ModelInspector;
    private ref FixedBottomDrawerTab? _pendingRightSidebarSection => ref _host.PendingRightSidebarSection;
    private PlacementEditService _placementEditing => _host.PlacementEditing;
    private Pm4WorkbenchService _pm4Workbench => _host.Pm4Workbench;
    private ProjectOutputService _projectOutput => _host.ProjectOutput;
    private ref string _projectOutputRootDir => ref _host.ProjectOutputRootDir;
    private ref ISceneRenderer? _renderer => ref _host.Renderer;
    private HashSet<(int tileX, int tileY, int chunkX, int chunkY)> _selectedChunks => _host.SelectedChunks;
    private ref int _selectedObjectIndex => ref _host.SelectedObjectIndex;
    private ref string _selectedObjectType => ref _host.SelectedObjectType;
    private ref string? _selectedPlacementSaveTargetPath => ref _host.SelectedPlacementSaveTargetPath;
    private SettingsWindowService _settingsWindow => _host.SettingsWindow;
    private ref bool _showLeftSidebar => ref _host.ShowLeftSidebar;
    private ref bool _showLogViewer => ref _host.ShowLogViewer;
    private ref bool _showMinimapWindow => ref _host.ShowMinimapWindow;
    private ref bool _showModelInfo => ref _host.ShowModelInfo;
    private ref bool _showPerfWindow => ref _host.ShowPerfWindow;
    private ref bool _showRightSidebar => ref _host.ShowRightSidebar;
    private TerrainControlsPanelService _terrainControlsPanel => _host.TerrainControlsPanel;
    private ref TerrainExportKind _terrainExportKind => ref _host.TerrainExportKind;
    private ref TerrainImportKind _terrainImportKind => ref _host.TerrainImportKind;
    private ref TerrainManager? _terrainManager => ref _host.TerrainManager;
    private ref bool _useTabUi => ref _host.UseTabUi;
    private ref VlmTerrainManager? _vlmTerrainManager => ref _host.VlmTerrainManager;
    private ref bool _wantExportGlb => ref _host.WantExportGlb;
    private ref bool _wantExportGlbCollision => ref _host.WantExportGlbCollision;
    private ref bool _wantTerrainExport => ref _host.WantTerrainExport;
    private ref bool _wantTerrainImport => ref _host.WantTerrainImport;
    private ref bool _workbenchOpen => ref _host.WorkbenchOpen;
    private WorkbenchPanelsService _workbenchPanels => _host.WorkbenchPanels;
    private ref WorkspaceMode _workspaceMode => ref _host.WorkspaceMode;
    private WorldObjectsPanelService _worldObjectsPanel => _host.WorldObjectsPanel;
    private ref WorldScene? _worldScene => ref _host.WorldScene;
    private void EnsureEditorHost() => _host.EnsureEditorHost();
}
