using System.Numerics;
using System.Diagnostics;
using System.Text.Json;
using ImGuiNET;
using WoWViewer.DataSources;
using WoWViewer.Workbench;
using WoWViewer.Logging;
using WoWViewer.Rendering;
using WoWViewer.Terrain;
using WowViewer.Core.Runtime.World;
using WowViewer.Core.Runtime.World.Passes;
using WowViewer.Core.Runtime.World.Visibility;
using WoWViewer.Population;
using WoWViewer.UI;
using ObjectInstance = WowViewer.Core.Runtime.World.WorldObjectInstance;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using WowViewer.Core.IO.Mdx;
using WoWViewer.Export;
using WoWViewer.Catalog;
using WoWViewer.Capture;
using Silk.NET.Input;
using Silk.NET.Maths;
using Silk.NET.OpenGL;
using Silk.NET.OpenGL.Extensions.ImGui;
using Silk.NET.Windowing;
using WowViewer.Core.IO.Files;
using WowViewer.Core.IO.Maps;
using WowViewer.Core.Maps;
using WoWViewer.Terrain.Vlm;
using WowViewer.Core.IO.M2;
using WowViewer.Core.IO.M2Chunked;
using WowViewer.Core.IO.M2Era1121;
using WowViewer.Core.M2;
using WowViewer.Core.Runtime.M2;
using WowViewer.Core.Runtime.Marketing;
using WowViewer.Core.IO.Converters;
using CoreMdxCollisionSummary = WowViewer.Core.Mdx.MdxCollisionSummary;
using CoreMdxGeometryFile = WowViewer.Core.Mdx.MdxGeometryFile;
using CoreMdxSummary = WowViewer.Core.Mdx.MdxSummary;
using CorePm4DocumentReader = WowViewer.Core.PM4.Services.Pm4ResearchReader;
using Pm4CoordinateService = WowViewer.Core.PM4.Services.Pm4CoordinateService;
using WowViewer.Core.Mdx;
using WowViewer.Core.Editor;
using WowViewer.Core.Editor.Bridge;
using WowViewer.Core.Editor.Eras;
using WowViewer.Core.Editor.Logging;
using WowViewer.Core.Editor.Operations;
using WowViewer.Core.Editor.Plugins;
using WowViewer.Core.Editor.Session;
using WowViewer.Core.PM4.Matching;
using WowViewer.Core.PM4.Reconciliation;
using WowViewer.Core.PM4.Services;
using WowViewer.Core.IO.Terrain;
using WowViewer.Core.Runtime.World.Minimap;
using System;
using static WoWViewer.ViewerApp;

namespace WoWViewer;

// WorkbenchPanelsService host bridge. Bridged member types are declared across ViewerApp partial files, so this
// file carries those files' using directives; the moved members keep their original usings.
internal sealed partial class WorkbenchPanelsService
{
    // Host bridge (same names as the former ViewerApp members).
    private ref int _activeBottomTabIndex => ref _host.ActiveBottomTabIndex;
    private ref WorkbenchTab _activeTopTab => ref _host.ActiveTopTab;
    private ref int _activeUtilitiesTabIndex => ref _host.ActiveUtilitiesTabIndex;
    private ArchaeologyPanelService _archaeologyPanel => _host.ArchaeologyPanel;
    private AudioPanelService _audioPanel => _host.AudioPanel;
    private ref Camera _camera => ref _host.Camera;
    private ref float _cameraSpeed => ref _host.CameraSpeed;
    private ref AssetCatalogView? _catalogView => ref _host.CatalogView;
    private ref ChunkClipboard? _chunkClipboard => ref _host.ChunkClipboard;
    private ref (int tileX, int tileY, int chunkX, int chunkY)? _chunkClipboardLockedTargetKey => ref _host.ChunkClipboardLockedTargetKey;
    private ref ChunkClipboardSet? _chunkClipboardSet => ref _host.ChunkClipboardSet;
    private ref string _chunkClipboardStatus => ref _host.ChunkClipboardStatus;
    private ref IDataSource? _dataSource => ref _host.DataSource;
    private ref EditorWorkspaceTask _editorWorkspaceTask => ref _host.EditorWorkspaceTask;
    private ref float _fovDegrees => ref _host.FovDegrees;
    private ref GL _gl => ref _host.Gl;
    private ref bool _hideUiChrome => ref _host.HideUiChrome;
    private InspectorPayloadsService _inspectorPayloads => _host.InspectorPayloads;
    private InvestigationService _investigation => _host.Investigation;
    private ref UtilitiesBottomTab? _legacyUtilityPage => ref _host.LegacyUtilityPage;
    private LightingPanelService _lightingPanel => _host.LightingPanel;
    private MainMenuBarService _mainMenuBar => _host.MainMenuBar;
    private ModelInspectorPanelService _modelInspector => _host.ModelInspector;
    private StandaloneModelLoaderService _modelLoader => _host.ModelLoader;
    private NavigatorPanelService _navigatorPanel => _host.NavigatorPanel;
    private ref ShellPanelId? _pendingFocusedShellPanel => ref _host.PendingFocusedShellPanel;
    private PlacementEditService _placementEditing => _host.PlacementEditing;
    private Pm4WorkbenchService _pm4Workbench => _host.Pm4Workbench;
    private ref ISceneRenderer? _renderer => ref _host.Renderer;
    private ref float _rightSidebarWidth => ref _host.RightSidebarWidth;
    private ref int _savedDetailedAdtTileCountOverride => ref _host.SavedDetailedAdtTileCountOverride;
    private ref int _selectedAreaPoiId => ref _host.SelectedAreaPoiId;
    private HashSet<(int tileX, int tileY, int chunkX, int chunkY)> _selectedChunks => _host.SelectedChunks;
    private ref string _selectedObjectInfo => ref _host.SelectedObjectInfo;
    private ref string _selectedObjectType => ref _host.SelectedObjectType;
    private ViewerSettingsService _settings => _host.Settings;
    private ShellLayoutService _shellLayout => _host.ShellLayout;
    private ref bool _showMapConverterDialog => ref _host.ShowMapConverterDialog;
    private ref bool _showRightSidebar => ref _host.ShowRightSidebar;
    private ref bool _showSettingsWindow => ref _host.ShowSettingsWindow;
    private ref bool _showWmoConverterDialog => ref _host.ShowWmoConverterDialog;
    private SqlSpawnStreamingService _sqlSpawnStreaming => _host.SqlSpawnStreaming;
    private TaxiAndAreaPoiSelectionService _taxiAndAreaPoi => _host.TaxiAndAreaPoi;
    private TaxiPanelService _taxiPanel => _host.TaxiPanel;
    private TerrainControlsPanelService _terrainControlsPanel => _host.TerrainControlsPanel;
    private ref TerrainManager? _terrainManager => ref _host.TerrainManager;
    private ThemesService _themes => _host.Themes;
    private ref bool _useDockspaceUi => ref _host.UseDockspaceUi;
    private ref bool _useTabUi => ref _host.UseTabUi;
    private ViewerChromeService _viewerChrome => _host.ViewerChrome;
    private ref VlmTerrainManager? _vlmTerrainManager => ref _host.VlmTerrainManager;
    private ref bool _wantExportGlb => ref _host.WantExportGlb;
    private ref bool _workbenchOpen => ref _host.WorkbenchOpen;
    private ref WorkspaceMode _workspaceMode => ref _host.WorkspaceMode;
    private WorldObjectsPanelService _worldObjectsPanel => _host.WorldObjectsPanel;
    private ref WorldScene? _worldScene => ref _host.WorldScene;
    private void DrawAuthoritativeFogControls(bool showDescription = true) => _host.DrawAuthoritativeFogControls(showDescription);
    private void DrawCapturePanelContent() => _host.DrawCapturePanelContent();
    private void DrawLogViewerContent() => _host.DrawLogViewerContent();
    private void DrawMinimapContent(int loadedTileCount, string? mapName, List<(int tx, int ty)> existingTiles, Func<int, int, bool> isTileLoaded) => _host.DrawMinimapContent(loadedTileCount, mapName, existingTiles, isTileLoaded);
    private void DrawRenderQualityContent() => _host.DrawRenderQualityContent();
    private void EnsureEditorHost() => _host.EnsureEditorHost();
    private Workbench.Pages.EditorWorkbenchPages EnsureEditorPages() => _host.EnsureEditorPages();
    private float GetTopChromeHeight() => _host.GetTopChromeHeight();
    private string GetWorkspaceSaveStatusSummary() => _host.GetWorkspaceSaveStatusSummary();
    private string GetWorkspaceTargetSummary() => _host.GetWorkspaceTargetSummary();
    private bool IsEditorTaskAvailable(EditorWorkspaceTask task) => _host.IsEditorTaskAvailable(task);
    private void ResetCamera() => _host.ResetCamera();
    private void SetEditorWorkspaceTask(EditorWorkspaceTask task) => _host.SetEditorWorkspaceTask(task);
    private bool TryGetActiveMinimapState(out List<(int tx, int ty)>? existingTiles, out Func<int, int, bool>? isTileLoaded, out int loadedTileCount, out string? mapName) => _host.TryGetActiveMinimapState(out existingTiles, out isTileLoaded, out loadedTileCount, out mapName);
}
