using System.Security.Cryptography;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using WowViewer.Core.IO.Blp;

namespace WowViewer.Core.Tests;

/// <summary>
/// Locks <see cref="Dxt1TileCodec"/> to the Python dataset codec
/// (<c>data-harvester/src/harvester/v50/dxt1_approx.py</c>).
///
/// WHY: the training dataset degrades synthetic minimaps to the authored DXT1 domain in Python, at
/// curriculum-build time, while the harvester's <c>--dxt1-parity</c> companion does it here in C#.
/// Two implementations of one lossy transform is only safe if they agree exactly — otherwise the
/// data a model trains on and the data we score against carry different codec noise, and every
/// comparison silently mixes two degradation classes.
///
/// The fixture is generated by pure integer arithmetic so both languages produce identical input
/// without shipping a binary asset. The expected hash is the SHA-256 of the round-tripped RGB bytes;
/// the mirrored Python assertion lives in <c>tests/v50/test_dxt1_approx.py</c>. If this test fails,
/// the two codecs have diverged — fix them together, never silence one side.
/// </summary>
public sealed class Dxt1PythonParityTests
{
    private const int Size = 64;

    private const string ExpectedSourceSha256 =
        "67306dac32c0c3d9db29f092aa35e15902885953f7f03311011a84299928aba4";

    private const string ExpectedRoundTripSha256 =
        "cdacc08445ba0e00ca5bb71bb04a5abea09fb9e71a0bf776cc51ff7fe6d3e451";

    private static Image<Rgba32> BuildFixture()
    {
        var image = new Image<Rgba32>(Size, Size);
        for (int y = 0; y < Size; y++)
        {
            for (int x = 0; x < Size; x++)
            {
                byte r = (byte)(((x * 7) + (y * 3)) % 256);
                byte g = (byte)(((x * x) + (y * 5)) % 256);
                byte b = (byte)(((x * 11) + (y * y)) % 256);
                image[x, y] = new Rgba32(r, g, b, 255);
            }
        }

        return image;
    }

    private static string Sha256OfRgb(Image<Rgba32> image)
    {
        byte[] rgb = new byte[image.Width * image.Height * 3];
        int i = 0;
        for (int y = 0; y < image.Height; y++)
        {
            for (int x = 0; x < image.Width; x++)
            {
                Rgba32 pixel = image[x, y];
                rgb[i++] = pixel.R;
                rgb[i++] = pixel.G;
                rgb[i++] = pixel.B;
            }
        }

        return Convert.ToHexString(SHA256.HashData(rgb)).ToLowerInvariant();
    }

    [Fact]
    public void Fixture_MatchesThePythonSideInput()
    {
        using Image<Rgba32> source = BuildFixture();
        Assert.Equal(ExpectedSourceSha256, Sha256OfRgb(source));
    }

    [Fact]
    public void EncodeDecode_MatchesThePythonDatasetCodecExactly()
    {
        using Image<Rgba32> source = BuildFixture();
        using Image<Rgba32> parity = Dxt1TileCodec.EncodeDecode(source);
        Assert.Equal(ExpectedRoundTripSha256, Sha256OfRgb(parity));
    }
}
