using System.Diagnostics;
using System.Numerics;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using ImGuiNET;
using WowViewer.Core.IO.Mdx;
using WoWViewer.DataSources;
using WoWViewer.Export;
using WoWViewer.Logging;
using WoWViewer.Rendering;
using WoWViewer.Catalog;
using WoWViewer.Capture;
using WoWViewer.Population;
using WoWViewer.Terrain;
using Silk.NET.Input;
using Silk.NET.Maths;
using Silk.NET.OpenGL;
using Silk.NET.OpenGL.Extensions.ImGui;
using Silk.NET.Windowing;
using WowViewer.Core.IO.Files;
using WowViewer.Core.IO.Maps;
using WowViewer.Core.Maps;
using WoWViewer.Terrain.Vlm;
using WowViewer.Core.IO.M2;
using WowViewer.Core.IO.M2Chunked;
using WowViewer.Core.IO.M2Era1121;
using WowViewer.Core.M2;
using WowViewer.Core.Runtime.M2;
using WowViewer.Core.Runtime.Marketing;
using WowViewer.Core.Runtime.World.Visibility;
using ObjectInstance = WowViewer.Core.Runtime.World.WorldObjectInstance;
using WowViewer.Core.IO.Converters;
using WoWViewer.Workbench;
using CoreMdxCollisionSummary = WowViewer.Core.Mdx.MdxCollisionSummary;
using CoreMdxGeometryFile = WowViewer.Core.Mdx.MdxGeometryFile;
using CoreMdxSummary = WowViewer.Core.Mdx.MdxSummary;
using CorePm4DocumentReader = WowViewer.Core.PM4.Services.Pm4ResearchReader;
using Pm4CoordinateService = WowViewer.Core.PM4.Services.Pm4CoordinateService;
using WowViewer.Core.Mdx;
using WowViewer.Core.Editor;
using WowViewer.Core.Editor.Bridge;
using WowViewer.Core.Editor.Eras;
using WowViewer.Core.Editor.Logging;
using WowViewer.Core.Editor.Operations;
using WowViewer.Core.Editor.Plugins;
using WowViewer.Core.Editor.Session;
using WowViewer.Core.PM4.Matching;
using WowViewer.Core.PM4.Reconciliation;
using WowViewer.Core.PM4.Services;
using WowViewer.Core.IO.Terrain;
using WowViewer.Core.Runtime.World;
using System.IO;
using WowViewer.Core.IO.Dbc;
using WowViewer.Core.Runtime.World.Passes;
using WoWViewer.UI;
using System.Globalization;
using WowViewer.Core.IO.Casc;
using static WoWViewer.ViewerApp;

namespace WoWViewer;

// ArchaeologyPanelService host bridge. Bridged member types are declared across ViewerApp partial files, so this
// file carries those files' using directives; the moved members keep their original usings.
internal sealed partial class ArchaeologyPanelService
{
    // Host bridge (same names as the former ViewerApp members).
    private ref int _activeBottomTabIndex => ref _host.ActiveBottomTabIndex;
    private ref int _activePm4TabIndex => ref _host.ActivePm4TabIndex;
    private ref bool _archeologyApplyToNextCapture => ref _host.ArcheologyApplyToNextCapture;
    private ref bool _archeologyApplyToVideoRecording => ref _host.ArcheologyApplyToVideoRecording;
    private ref int _archeologyMaxUniqueId => ref _host.ArcheologyMaxUniqueId;
    private ref int _archeologyMinUniqueId => ref _host.ArcheologyMinUniqueId;
    private ref bool _archeologyPlaybackActive => ref _host.ArcheologyPlaybackActive;
    private ref bool _archeologyPlaybackLoop => ref _host.ArcheologyPlaybackLoop;
    private ref float _archeologyPlaybackSpeed => ref _host.ArcheologyPlaybackSpeed;
    private ref int _archeologyScopeIndex => ref _host.ArcheologyScopeIndex;
    private ref Camera _camera => ref _host.Camera;
    private CascAhdrSourceService _cascAhdrSource => _host.CascAhdrSource;
    private DataSourceSessionService _dataSourceSession => _host.DataSourceSession;
    private ref string? _dbcBuild => ref _host.DbcBuild;
    private ref DBCD.Providers.IDBCProvider? _dbcProvider => ref _host.DbcProvider;
    private ref string? _dbdDir => ref _host.DbdDir;
    private ref List<MapDefinition> _discoveredMaps => ref _host.DiscoveredMaps;
    private ref EditorSession? _editorSession => ref _host.EditorSession;
    private ref MapListSortMode _mapListSortMode => ref _host.MapListSortMode;
    private Pm4WorkbenchService _pm4Workbench => _host.Pm4Workbench;
    private ProjectOutputService _projectOutput => _host.ProjectOutput;
    private ViewerSettingsService _settings => _host.Settings;
    private ref bool _showSynthesizedMinimapExportDialog => ref _host.ShowSynthesizedMinimapExportDialog;
    private ref bool _showUniqueIdArchaeologyWindow => ref _host.ShowUniqueIdArchaeologyWindow;
    private ref string _statusMessage => ref _host.StatusMessage;
    private ref TerrainExportKind _terrainExportKind => ref _host.TerrainExportKind;
    private ref TerrainManager? _terrainManager => ref _host.TerrainManager;
    private ref bool _wantExportGlb => ref _host.WantExportGlb;
    private ref bool _wantExportGlbCollision => ref _host.WantExportGlbCollision;
    private ref bool _wantTerrainExport => ref _host.WantTerrainExport;
    private ref WorldScene? _worldScene => ref _host.WorldScene;
    private void DrawCapturePanelContent() => _host.DrawCapturePanelContent();
    private void DrawMapSortModeSelector(string id) => _host.DrawMapSortModeSelector(id);
    private void DrawSynthesizedMinimapExportContent(bool showCloseButton = false) => _host.DrawSynthesizedMinimapExportContent(showCloseButton);
    private void DrawTemporalStratigraphySubTab() => _host.DrawTemporalStratigraphySubTab();
    private void DrawTerrainControlsAdjustmentWeakSignalContent() => _host.DrawTerrainControlsAdjustmentWeakSignalContent();
    private void DrawVisualInvestigationToolbox(bool showWorldObjectRangeControls) => _host.DrawVisualInvestigationToolbox(showWorldObjectRangeControls);
    private void EnsureEditorHost() => _host.EnsureEditorHost();
    private void OpenWorkbenchTab(WorkbenchTab topTab, int bottomIndex = -1) => _host.OpenWorkbenchTab(topTab, bottomIndex);
    private void OpenWorkbenchTab(ModelBottomTab tab) => _host.OpenWorkbenchTab(tab);
    private void OpenWorkbenchTab(WorldBottomTab tab) => _host.OpenWorkbenchTab(tab);
    private void OpenWorkbenchTab(ToolsBottomTab tab) => _host.OpenWorkbenchTab(tab);
    private void OpenWorkbenchTab(UtilitiesBottomTab tab) => _host.OpenWorkbenchTab(tab);
    private void PrepareSynthesizedMinimapExportDialogInputs() => _host.PrepareSynthesizedMinimapExportDialogInputs();
}
