using System.Diagnostics;
using System.Numerics;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using ImGuiNET;
using WowViewer.Core.IO.Mdx;
using WoWViewer.DataSources;
using WoWViewer.Export;
using WoWViewer.Logging;
using WoWViewer.Rendering;
using WoWViewer.Catalog;
using WoWViewer.Capture;
using WoWViewer.Population;
using WoWViewer.Terrain;
using Silk.NET.Input;
using Silk.NET.Maths;
using Silk.NET.OpenGL;
using Silk.NET.OpenGL.Extensions.ImGui;
using Silk.NET.Windowing;
using WowViewer.Core.IO.Files;
using WowViewer.Core.IO.Maps;
using WowViewer.Core.Maps;
using WoWViewer.Terrain.Vlm;
using WowViewer.Core.IO.M2;
using WowViewer.Core.IO.M2Chunked;
using WowViewer.Core.IO.M2Era1121;
using WowViewer.Core.M2;
using WowViewer.Core.Runtime.M2;
using WowViewer.Core.Runtime.Marketing;
using WowViewer.Core.Runtime.World.Visibility;
using ObjectInstance = WowViewer.Core.Runtime.World.WorldObjectInstance;
using WowViewer.Core.IO.Converters;
using WoWViewer.Workbench;
using CoreMdxCollisionSummary = WowViewer.Core.Mdx.MdxCollisionSummary;
using CoreMdxGeometryFile = WowViewer.Core.Mdx.MdxGeometryFile;
using CoreMdxSummary = WowViewer.Core.Mdx.MdxSummary;
using CorePm4DocumentReader = WowViewer.Core.PM4.Services.Pm4ResearchReader;
using Pm4CoordinateService = WowViewer.Core.PM4.Services.Pm4CoordinateService;
using WowViewer.Core.Mdx;
using System.Globalization;
using MslkEntry = WowViewer.Core.PM4.Models.Pm4MslkEntry;
using System;
using WowViewer.Core.Runtime.World;
using WowViewer.Core.Runtime.World.Passes;
using WoWViewer.UI;
using WowViewer.Core.IO.Casc;
using static WoWViewer.ViewerApp;
using static WoWViewer.CameraPathsService;

namespace WoWViewer;

// MainMenuBarService host bridge. Bridged member types are declared across ViewerApp partial files, so this
// file carries those files' using directives; the moved members keep their original usings.
internal sealed partial class MainMenuBarService
{
    // Host bridge (same names as the former ViewerApp members).
    private ref int _activeUtilitiesTabIndex => ref _host.ActiveUtilitiesTabIndex;
    private CascAhdrSourceService _cascAhdrSource => _host.CascAhdrSource;
    private ref AssetCatalogView? _catalogView => ref _host.CatalogView;
    private ClientDialogsService _clientDialogs => _host.ClientDialogs;
    private ConverterDialogsService _converterDialogs => _host.ConverterDialogs;
    private ref IDataSource? _dataSource => ref _host.DataSource;
    private DataSourceSessionService _dataSourceSession => _host.DataSourceSession;
    private ref string _datasetCatalogRoot => ref _host.DatasetCatalogRoot;
    private ref string _folderInputBuf => ref _host.FolderInputBuf;
    private ref bool _forceApplyShellPanelLayout => ref _host.ForceApplyShellPanelLayout;
    private ref GL _gl => ref _host.Gl;
    private ref bool _hideUiChrome => ref _host.HideUiChrome;
    private ref List<KnownGoodClientPath> _knownGoodClientPaths => ref _host.KnownGoodClientPaths;
    private ref string _lastGameFolderPath => ref _host.LastGameFolderPath;
    private ref string _lastLooseOverlayPath => ref _host.LastLooseOverlayPath;
    private ref UtilitiesBottomTab? _legacyUtilityPage => ref _host.LegacyUtilityPage;
    private ref string? _loadedFileName => ref _host.LoadedFileName;
    private ref string? _loadedFilePath => ref _host.LoadedFilePath;
    private ref MdxFile? _loadedMdx => ref _host.LoadedMdx;
    private ref WmoV14ToV17Converter.WmoV14Data? _loadedWmo => ref _host.LoadedWmo;
    private ref string _mapConvertLkMapDir => ref _host.MapConvertLkMapDir;
    private ref string _mapConvertSourcePath => ref _host.MapConvertSourcePath;
    private ref TerrainTileScope _mapGlbScope => ref _host.MapGlbScope;
    private ref Md5TranslateIndex? _md5Index => ref _host.Md5Index;
    private StandaloneModelLoaderService _modelLoader => _host.ModelLoader;
    private ref bool _openForgetKnownGoodClientConfirm => ref _host.OpenForgetKnownGoodClientConfirm;
    private ref string? _pendingForgetKnownGoodClientDisplayName => ref _host.PendingForgetKnownGoodClientDisplayName;
    private ref string? _pendingForgetKnownGoodClientPath => ref _host.PendingForgetKnownGoodClientPath;
    private ref bool _pendingKnownGoodClientAttachLooseFolder => ref _host.PendingKnownGoodClientAttachLooseFolder;
    private ref string? _pendingKnownGoodClientBuildVersion => ref _host.PendingKnownGoodClientBuildVersion;
    private ref string? _pendingKnownGoodClientPath => ref _host.PendingKnownGoodClientPath;
    private ref ISceneRenderer? _renderer => ref _host.Renderer;
    private ViewerSettingsService _settings => _host.Settings;
    private ShellLayoutService _shellLayout => _host.ShellLayout;
    private ref bool _showFileBrowser => ref _host.ShowFileBrowser;
    private ref bool _showFolderInput => ref _host.ShowFolderInput;
    private ref bool _showLeftSidebar => ref _host.ShowLeftSidebar;
    private ref bool _showLogViewer => ref _host.ShowLogViewer;
    private ref bool _showMapConverterDialog => ref _host.ShowMapConverterDialog;
    private ref bool _showModelInfo => ref _host.ShowModelInfo;
    private ref bool _showPerfWindow => ref _host.ShowPerfWindow;
    private ref bool _showRightSidebar => ref _host.ShowRightSidebar;
    private ref bool _showSettingsWindow => ref _host.ShowSettingsWindow;
    private ref bool _showSynthesizedMinimapExportDialog => ref _host.ShowSynthesizedMinimapExportDialog;
    private ref bool _showWmoConverterDialog => ref _host.ShowWmoConverterDialog;
    private ref string _statusMessage => ref _host.StatusMessage;
    private ref TerrainExportKind _terrainExportKind => ref _host.TerrainExportKind;
    private ref TerrainImportKind _terrainImportKind => ref _host.TerrainImportKind;
    private ref TerrainManager? _terrainManager => ref _host.TerrainManager;
    private TerrainTileIoService _terrainTileIo => _host.TerrainTileIo;
    private ref string _terrainTransferOutputDir => ref _host.TerrainTransferOutputDir;
    private ref string _terrainTransferSourceDir => ref _host.TerrainTransferSourceDir;
    private ref string _terrainTransferTargetDir => ref _host.TerrainTransferTargetDir;
    private ref bool _useDockspaceUi => ref _host.UseDockspaceUi;
    private ref bool _useTabUi => ref _host.UseTabUi;
    private ref string _vlmClientPath => ref _host.VlmClientPath;
    private ref string _vlmMapName => ref _host.VlmMapName;
    private ref string _vlmOutputDir => ref _host.VlmOutputDir;
    private ref VlmTerrainManager? _vlmTerrainManager => ref _host.VlmTerrainManager;
    private ref bool _wantExportGlb => ref _host.WantExportGlb;
    private ref bool _wantExportGlbCollision => ref _host.WantExportGlbCollision;
    private ref bool _wantExportMapGlbTiles => ref _host.WantExportMapGlbTiles;
    private ref bool _wantOpenFile => ref _host.WantOpenFile;
    private ref bool _wantSelectDatasetCatalogRoot => ref _host.WantSelectDatasetCatalogRoot;
    private ref bool _wantTerrainExport => ref _host.WantTerrainExport;
    private ref bool _wantTerrainImport => ref _host.WantTerrainImport;
    private ref IWindow _window => ref _host.Window;
    private ref string _wmoConvertSourcePath => ref _host.WmoConvertSourcePath;
    private ref bool _workbenchOpen => ref _host.WorkbenchOpen;
    private ref WorkspaceMode _workspaceMode => ref _host.WorkspaceMode;
    private WorldLoaderService _worldLoader => _host.WorldLoader;
    private ref WorldScene? _worldScene => ref _host.WorldScene;
    private ViewerKeyContext GetActiveKeyContext() => _host.GetActiveKeyContext();
    private void OpenCapturePanelTab(CapturePanelTab tab) => _host.OpenCapturePanelTab(tab);
    private void OpenPm4Workbench(Pm4WorkbenchTab tab) => _host.OpenPm4Workbench(tab);
    private void OpenWorkbenchTab(WorkbenchTab topTab, int bottomIndex = -1) => _host.OpenWorkbenchTab(topTab, bottomIndex);
    private void OpenWorkbenchTab(ModelBottomTab tab) => _host.OpenWorkbenchTab(tab);
    private void OpenWorkbenchTab(WorldBottomTab tab) => _host.OpenWorkbenchTab(tab);
    private void OpenWorkbenchTab(ToolsBottomTab tab) => _host.OpenWorkbenchTab(tab);
    private void OpenWorkbenchTab(UtilitiesBottomTab tab) => _host.OpenWorkbenchTab(tab);
    private void PrepareSynthesizedMinimapExportDialogInputs() => _host.PrepareSynthesizedMinimapExportDialogInputs();
    private void RefreshDatasetCatalog() => _host.RefreshDatasetCatalog();
    private void ResetCamera() => _host.ResetCamera();
    private void SetWorkspaceMode(WorkspaceMode mode) => _host.SetWorkspaceMode(mode);
}
