using System.IO;
using WoWFormatLib.Structs.WMO;

namespace ParpToolbox
{
    public static class ObjExporter
    { 
        public static void Export(WMO wmo, string filename)
        {
            // Temporary stub: will be replaced by real implementation once WmoGroup abstraction is wired.
            var dir = Path.GetDirectoryName(filename) ?? ".";
            Directory.CreateDirectory(dir);
            File.WriteAllText(filename, "# Stub OBJ generated by parpToolbox\n");
        }

        private static void WriteMtlFile(WMO wmo, string mtlPath)
        {
            // Stub material file
            File.WriteAllText(mtlPath, "# Stub MTL generated by parpToolbox\n");
        }
    }
}
